package de.craftorio.datagen;

import de.craftorio.Craftorio;
import de.craftorio.registry.ModBlocks;
import de.craftorio.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public final class ModLanguageProvider {
    private ModLanguageProvider() {
    }

    public static final class English extends LanguageProvider {
        public English(PackOutput output) {
            super(output, Craftorio.MOD_ID, "en_us");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Cap Rock");
            add(ModBlocks.TRADING_POST.get(), "Trading Post");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Iron Ore Field");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Copper Ore Field");
            add(ModBlocks.COAL_FIELD.get(), "Coal Field");
            add(ModBlocks.BURNER_DRILL.get(), "Burner Drill");
            add(ModBlocks.CONVEYOR_BELT.get(), "Conveyor Belt");
            add(ModBlocks.INSERTER.get(), "Inserter");

            add(ModBlocks.COAL_GENERATOR.get(), "Coal Generator");
            add(ModBlocks.POWER_POLE.get(), "Power Pole");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Electric Furnace");
            add(ModBlocks.PRESS.get(), "Press");
            add(ModBlocks.ASSEMBLER.get(), "Assembler");
            add(ModItems.IRON_PLATE.get(), "Iron Plate");
            add(ModItems.COPPER_CABLE.get(), "Copper Cable");
            add(ModItems.IRON_GEAR.get(), "Iron Gear");
            add(ModItems.CIRCUIT.get(), "Circuit");
            add(ModItems.MOTOR.get(), "Motor");

            add("craftorio.gui.energy", "Energy: %s / %s FE");
            add("craftorio.gui.no_recipe", "Choose a recipe");
            add("craftorio.power.no_network", "Not connected");
            add("craftorio.power.network", "Grid: %s poles · %s generators · %s consumers · %s/%s FE/t · %s%% supplied");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Construction Workbench");
            add(ModBlocks.ASSEMBLY_WORKBENCH.get(), "Assembly Workbench");
            add(ModBlocks.PRECISION_WORKBENCH.get(), "Precision Workbench");
            add(ModItems.WORKBENCH_UPGRADE_2.get(), "Workbench Upgrade Kit (Tier 2)");
            add(ModItems.WORKBENCH_UPGRADE_3.get(), "Workbench Upgrade Kit (Tier 3)");
            add(ModItems.DRILL_CORE.get(), "Drill Core");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonance Crystal");
            add(ModItems.DEEP_CORE.get(), "Deep Core");
            add(ModItems.STAR_SHARD.get(), "Star Shard");

            add("craftorio.key_material.hint", "Key material – reward for tower defense level %s");
            add("craftorio.workbench.upgrade_hint", "Right-click a tier %s workbench to upgrade it");
            add("craftorio.workbench.upgrade_target", "Only works on a tier %s workbench");
            add("craftorio.workbench.hint", "Click: build 1 · Shift-click: build 10");
            add("craftorio.workbench.build", "Build");
            add("craftorio.workbench.locked", "Locked");
            add("craftorio.workbench.needs_tier", "Needs workbench tier %s");
            add("craftorio.workbench.tier_too_low", "This blueprint needs a tier %s workbench");
            add("craftorio.workbench.missing", "Missing materials");
            add("craftorio.terminal.tab.blueprints", "Blueprints");
            add("craftorio.terminal.tab.stats", "Statistics");
            add("craftorio.terminal.unlock", "Unlock");
            add("craftorio.terminal.stats.earned", "Total earned");
            add("craftorio.terminal.stats.spent", "Total spent");
            add("craftorio.terminal.stats.recent", "Earned in the last 10 minutes");
            add("craftorio.terminal.stats.top", "Best sellers");
            add("craftorio.blueprint.tier", "Tier %s");
            add("craftorio.blueprint.requires", "needs %s");
            add("craftorio.blueprint.materials", "Materials:");
            add("craftorio.blueprint.unlock_items", "Unlock also needs:");
            add("craftorio.blueprint.unlocked", "Blueprint %s unlocked for %s");
            add("craftorio.blueprint.locked", "This blueprint is not unlocked yet");
            add("craftorio.blueprint.status.unlocked", "unlocked");
            add("craftorio.blueprint.status.available", "available");
            add("craftorio.blueprint.status.missing_prerequisite", "Unlock the prerequisite first");
            add("craftorio.blueprint.status.missing_key_items", "needs key material");
            add("craftorio.blueprint.status.not_enough_credits", "not enough credits");

            add(ModBlocks.ZONE_CORE.get(), "Zone Core");
            add(ModBlocks.ENEMY_PORTAL.get(), "Enemy Portal");
            add(ModBlocks.PATH_BLOCK.get(), "Path Block");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Crossbow Tower");
            add(ModBlocks.GUN_TURRET.get(), "Gun Turret");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla Tower");
            add(ModBlocks.TOWER_RUIN.get(), "Tower Ruin");
            add(ModItems.BOLT.get(), "Bolt");
            add(ModItems.CARTRIDGE.get(), "Cartridge");
            add("entity.craftorio.crawler", "Crawler");
            add("entity.craftorio.breaker", "Breaker");
            add("entity.craftorio.spitter", "Spitter");
            add("entity.craftorio.brood_mother", "Brood Mother");

            add("craftorio.terminal.tab.defense", "Defense");
            add("craftorio.hud.td", "Level %s · wave %s/%s · lives %s/%s · %s enemies");
            add("craftorio.td.next_level", "Next level");
            add("craftorio.td.wave", "Wave");
            add("craftorio.td.lives", "Lives");
            add("craftorio.td.enemies", "Enemies left");
            add("craftorio.td.reward", "Reward");
            add("craftorio.td.milestone", "Next key material");
            add("craftorio.td.milestone.in", "in %s levels");
            add("craftorio.td.key_next", "This level awards a key material!");
            add("craftorio.td.rules", "A level is lost when %s lives are gone. Enemies only attack towers – your factory is safe. Destroyed towers leave ruins you can rebuild.");
            add("craftorio.td.button.start", "Start level %s");
            add("craftorio.td.button.auto_on", "Auto-continue: on");
            add("craftorio.td.button.auto_off", "Auto-continue: off");
            add("craftorio.td.button.repair", "Repair all towers (%s)");
            add("craftorio.td.started", "Level %s started!");
            add("craftorio.td.won", "Level %s won! +%s");
            add("craftorio.td.lost", "Level %s lost – repair or upgrade your towers and try again.");
            add("craftorio.td.repair.nothing", "Nothing to repair.");
            add("craftorio.td.repair.too_expensive", "Not enough credits (%s needed).");
            add("craftorio.td.repair.done", "Towers repaired for %s.");
            add("craftorio.td.error.no_zone", "Your team has no defense zone.");
            add("craftorio.td.error.running", "A level is already running.");
            add("craftorio.td.error.no_portal", "The zone has no enemy portal.");
            add("craftorio.td.error.no_team", "You are not in a team.");
            add("craftorio.td.error.zone_exists", "Your team already has a zone core.");
            add("craftorio.td.error.overworld_only", "Defense zones only work in the overworld.");
            add("craftorio.td.error.outside_zone", "Only inside your defense zone (%s blocks around the zone core).");
            add("craftorio.td.error.foreign_zone", "This zone core belongs to another team.");
            add("craftorio.td.error.path.no_start", "No path block next to the enemy portal.");
            add("craftorio.td.error.path.branch", "The path branches – it must be a single line.");
            add("craftorio.td.error.path.dead_end", "The path ends before it reaches the zone core.");
            add("craftorio.td.error.path.too_short", "The path is too short (at least %s blocks).");
            add("craftorio.td.error.path.too_long", "The path is too long.");
            add("craftorio.tower.upgrade", "Upgrade");
            add("craftorio.tower.level", "Level %s");
            add("craftorio.tower.upgraded", "Tower upgraded to level %s for %s");
            add("craftorio.tower.rebuilt", "Tower rebuilt for %s");

            add(ModBlocks.CAVE_RUBBLE.get(), "Cave Rubble");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Cave Entrance");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Tin Ore Field");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Lead Ore Field");
            add(ModBlocks.SULFUR_FIELD.get(), "Sulfur Field");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Gold Ore Field");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quartz Field");
            add(ModItems.RAW_TIN.get(), "Raw Tin");
            add(ModItems.TIN_INGOT.get(), "Tin Ingot");
            add(ModItems.RAW_LEAD.get(), "Raw Lead");
            add(ModItems.LEAD_INGOT.get(), "Lead Ingot");
            add(ModItems.SULFUR.get(), "Sulfur");
            add(ModItems.BATTERY.get(), "Battery");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Advanced Circuit");
            add(ModBlocks.ELEVATOR.get(), "Item Elevator");
            add("craftorio.elevator.mode.receive", "Mode: receive (outputs through the front)");
            add("craftorio.elevator.mode.send_up", "Mode: send up");
            add("craftorio.elevator.mode.send_down", "Mode: send down");
            add("craftorio.elevator.target", "→ partner %s blocks away");
            add("craftorio.elevator.no_target", "→ no elevator in this column!");
            add("craftorio.cave.needs", "Construction site needs:");
            add("craftorio.cave.drilling", "Drilling: %s%% (needs %s FE/t from a power pole)");
            add("craftorio.cave.open", "Cave entrance open – take the scaffolding down (sneak to descend).");
            add("craftorio.cave.opened", "A cave entrance has opened! The cave area around chunk %s, %s is being dug out.");
            add("craftorio.cave.error.overworld_only", "Cave entrances only work in the overworld.");
            add("craftorio.cave.error.too_deep", "Build cave entrances on the surface (Y 50 or higher).");
            add("craftorio.cave.error.no_layer", "There is no cave layer below this spot (area generated before the cave update).");

            add("craftorio.drill.status", "Drill: %s/%s field blocks · %s items/s · fuel for %s s");
            add("craftorio.drill.overlap", "Too close to another drill – mining areas must not overlap.");
            add(ModBlocks.MINE_RUBBLE.get(), "Mine Rubble");
            add(ModBlocks.MINE_SHAFT.get(), "Mine Shaft");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamond Field");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanium Ore Field");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranium Ore Field");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Crystal Field");
            add(ModItems.RAW_TITANIUM.get(), "Raw Titanium");
            add(ModItems.TITANIUM_INGOT.get(), "Titanium Ingot");
            add(ModItems.TITANIUM_PLATE.get(), "Titanium Plate");
            add(ModItems.RAW_URANIUM.get(), "Raw Uranium");
            add(ModItems.URANIUM_PELLET.get(), "Uranium Pellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Crystal Shard");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energy Crystal");
            add(ModItems.FUEL_ROD.get(), "Fuel Rod");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Electric Drill");
            add(ModBlocks.DEEP_DRILL.get(), "Deep Drill");
            add(ModBlocks.FAST_BELT.get(), "Fast Belt");
            add(ModBlocks.EXPRESS_BELT.get(), "Express Belt");
            add(ModBlocks.REACTOR.get(), "Reactor");
            add(ModBlocks.LASER_TOWER.get(), "Laser Tower");
            add("entity.craftorio.crystal_golem", "Crystal Golem");
            add("craftorio.command.layer_unlocked", "Unlocked %s chunks of the layer (Y %s to %s); they are being dug out.");
            add("craftorio.mine.open", "Mine shaft open – take the scaffolding down into the mine layer.");
            add("craftorio.mine.opened", "A mine shaft has opened! The mine area around chunk %s, %s is being dug out.");
            add("craftorio.mine.error.not_in_caves", "Build mine shafts in an unlocked area of the cave layer (Y 0 to 39).");
            add("craftorio.drill.status_electric", "Drill: %s/%s field blocks · %s items/s · %s FE stored (needs %s FE/t)");

            add("craftorio.tooltip.sell_price", "Sell value: %s");
            add("craftorio.tooltip.sell_price_stack", "Sell value: %s (stack: %s)");
            add("craftorio.trading_post.sold", "Sold for %s");
            add("craftorio.trading_post.info", "Trading post of team %s – earned so far: %s");

            add("craftorio.command.credits", "Team %s has %s");
            add("craftorio.command.team.info", "Team %s – balance: %s – members: %s");
            add("craftorio.command.team.list_entry", "%s (%s members)");
            add("craftorio.command.team.created", "Team %s created.");
            add("craftorio.command.team.invited", "%s invited you to team %s.");
            add("craftorio.command.team.invite_sent", "Invitation sent to %s.");
            add("craftorio.command.team.joined", "You joined team %s.");
            add("craftorio.command.team.left", "You left your team and now play as team %s.");

            add("craftorio.team.error.name_taken", "A team named %s already exists.");
            add("craftorio.team.error.invalid_name", "Team names must be 1–%s characters: letters, digits, spaces, _ and -.");
            add("craftorio.team.error.no_team", "You are not in a team.");
            add("craftorio.team.error.already_member", "That player is already in this team.");
            add("craftorio.team.error.unknown_team", "There is no team named %s.");
            add("craftorio.team.error.not_invited", "You have not been invited to team %s.");
            add("craftorio.team.error.alone", "You are the only member of your team.");
            add("craftorio.command.team.rights", "Leader: %s – spending: %s");
            add("craftorio.command.team.spending.all", "all members");
            add("craftorio.command.team.spending.leader", "leader only");
            add("craftorio.command.team.spending.set_all", "All members may now spend the team's credits.");
            add("craftorio.command.team.spending.set_leader", "Only the leader may spend the team's credits now.");
            add("craftorio.command.team.kicked", "%s was removed from the team.");
            add("craftorio.command.team.kicked_you", "You were removed from team %s and now play in your own team.");
            add("craftorio.command.team.new_leader", "%s now leads the team.");
            add("craftorio.team.error.not_leader", "Only the team leader can do that.");
            add("craftorio.team.error.not_member", "That player is not in your team.");
            add("craftorio.team.error.kick_self", "You cannot kick yourself – use /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Only your team leader may spend credits.");
            add("craftorio.team.error.one_player", "Name exactly one player.");
            add("craftorio.protection.denied", "This belongs to team %s.");
            add("craftorio.protection.too_close", "Too close to team %s – keep one block of space to their machines and containers.");
            add("emi.category.craftorio.pressing", "Pressing");
            add("emi.category.craftorio.assembling", "Assembling");
            add("emi.category.craftorio.blueprint", "Blueprint (workbench)");
            add("craftorio.emi.time", "%s s");
            add("craftorio.emi.free", "free");
            add("config.jade.plugin_craftorio.status", "Craftorio status");
            add("config.jade.plugin_craftorio.ore_field", "Craftorio ore fields");
            add("craftorio.jade.owner", "Owner: team %s");
            add("craftorio.jade.progress", "Progress: %s%%");
            add("craftorio.jade.tower", "HP %s / %s · level %s");
            add("craftorio.jade.ammo", "Ammunition: %s");
            add("craftorio.jade.ruin", "Destroyed – rebuild for %s");
            add("craftorio.jade.ore_field", "Yields %s (%s each) – endless");
            add("craftorio.terminal.tab.quests", "Guide");
            add(ModItems.GUIDE_BOOK.get(), "Craftorio Handbook");
            add("key.craftorio.guide", "Open handbook");
            add("key.categories.craftorio", "Craftorio");
            add("craftorio.guide.current", "Current");
            add("craftorio.guide.step", "Guide · step %s of %s");
            add("craftorio.guide.progress", "Progress: %s");
            add("craftorio.guide.reward", "Reward: %s");
            add("craftorio.guide.buy_in_terminal", "Buy the blueprint in the terminal (%s), then build it at a workbench:");
            add("craftorio.guide.build_at", "Build at the %s from:");
            add("craftorio.guide.key", "Key:");
            add("craftorio.guide.crafting", "Recipe for the %s:");
            add("craftorio.guide.vanilla_table", "(normal crafting table)");
            add("craftorio.guide.upgrade_bench", "Needs a workbench of tier %s: buy the upgrade kit in the terminal and right-click your workbench with it.");
            add("craftorio.guide.value", "Sells for %s each");
            add("craftorio.guide.mined_from", "Mined from the %s – drill or by hand");
            add("craftorio.guide.made_in", "Made in the %s from:");
            add("craftorio.guide.smelted", "Smelted in a furnace or electric furnace:");
            add("craftorio.guide.earn", "Sell processed goods: the more processing steps, the higher the price. The terminal's statistics show what pays best.");
            add("craftorio.guide.defense", "Tower defense: go through your arena gate, lay a path with the path wand from the open gate to the core, place towers next to it and start the level in the terminal (Defense tab).");
            add("craftorio.hud.guide_key", "[%s] handbook");
            add("craftorio.arena.error.overworld_only", "Arena gates only work in the overworld.");
            add("craftorio.arena.error.not_arena", "Only in your arena.");
            add("craftorio.arena.error.outside_field", "Only inside the arena field.");
            add("craftorio.arena.error.foreign", "This is another team's arena.");
            add("craftorio.arena.error.no_tower_here", "Towers only stand on open ground or on a plateau – not on the path, trees, rock, water or lava.");
            add("craftorio.arena.error.no_building", "The arena cannot be changed – lay the path with the path wand and place towers.");
            add("craftorio.arena.path.blocked", "The path cannot go there.");
            add("craftorio.arena.path_wand.tooltip", "Click the arena floor to lay path; the next click in the same row or column draws a straight line. Sneak-click removes path or starts a new line.");
            add("craftorio.arena.welcome", "Arena · level %s · map: %s – %s");
            add("craftorio.arena.new_map", "The arena has changed: new map %s. Your towers are waiting in the tower depot – lay a new path!");
            add("craftorio.arena.old_core", "Defense zones are now arenas – build an arena gate (free blueprint) and step through.");
            add("craftorio.arena.theme.forest", "Forest");
            add("craftorio.arena.theme.forest.rule", "Enemies in the thicket are camouflaged: towers spot them only at half range.");
            add("craftorio.arena.theme.mountain", "Mountains");
            add("craftorio.arena.theme.mountain.rule", "Towers on plateaus reach 30 % further; scree slows enemies.");
            add("craftorio.arena.theme.fire", "Fire");
            add("craftorio.arena.theme.fire.rule", "Lava vents erupt every few seconds and burn enemies walking over them.");
            add("craftorio.arena.theme.water", "Water");
            add("craftorio.arena.theme.water.rule", "The river can only be crossed at fords; shallow water slows enemies a lot.");
            add("craftorio.arena.theme.colosseum", "Colosseum");
            add("craftorio.arena.theme.colosseum.rule", "Boss level: open sand between pillars.");
            add("craftorio.arena.mutator.fog", "Mutator Fog: towers see 25 % less far (+25 % reward).");
            add("craftorio.arena.mutator.haste", "Mutator Forced march: enemies are 30 % faster (+25 % reward).");
            add("craftorio.arena.mutator.hardened", "Mutator Hardened: enemies have 35 % more health (+30 % reward).");
            add("craftorio.arena.depot.empty", "The tower depot is empty.");
            add("craftorio.arena.depot.taken", "Took %s stacks from the tower depot.");
            add("craftorio.arena.feeder.status", "Arena reserve: %s / %s FE · %s bolts · %s cartridges");
            add("craftorio.arena.feeder.no_owner", "This feeder belongs to no team.");
            add("craftorio.arena.feeder.no_arena", "Your team has no arena yet – go through an arena gate first.");
            add("craftorio.td.error.not_running", "No level is running.");
            add("craftorio.td.call.not_now", "The next wave can only be called between waves.");
            add("craftorio.td.call.done", "Next wave called early! +%s");
            add("craftorio.td.won_stars", "Level %s won %s! +%s");
            add("craftorio.td.button.call", "Call wave");
            add("craftorio.td.map", "Map");
            add("craftorio.td.last_stars", "Last level");
            add("craftorio.td.preview", "Next wave:");
            add("craftorio.td.reserves", "Arena reserve: %s FE · %s bolts · %s cartridges");
            add("craftorio.tower.target.first", "Target: first");
            add("craftorio.tower.target.last", "Target: last");
            add("craftorio.tower.target.strongest", "Target: strongest");
            add("craftorio.tower.target.weakest", "Target: weakest");
            add("craftorio.quest.build_arena_gate", "Build an arena gate");
            add("craftorio.quest.build_arena_gate.hint", "Build the arena gate (free blueprint), place it and right-click it: it takes you to your own arena. There, lay a path from the open gate in the west wall to the core in the east wall with the path wand.");
            add("craftorio.td.help", "No arena yet. Build an arena gate (free blueprint), place it in the overworld and right-click it. In your arena lay a path with the path wand from the open enemy gate to the core, then place towers on open ground. Every won level brings a new map.");
            add("craftorio.td.key_reward", "Key material %s is waiting in the tower depot!");
            add("craftorio.td.path_ok", "Path OK: %s blocks from the gate to the core.");
            add(ModBlocks.ARENA_BASE.get(), "Arena Floor");
            add(ModBlocks.ARENA_CLIFF.get(), "Plateau Rock");
            add(ModBlocks.ARENA_GATE.get(), "Arena Gate");
            add(ModBlocks.ARENA_EXIT.get(), "Arena Exit");
            add(ModBlocks.TOWER_DEPOT.get(), "Tower Depot");
            add(ModBlocks.ARENA_FEEDER.get(), "Arena Feeder");
            add(ModItems.PATH_WAND.get(), "Path Wand");
            add("craftorio.quest.build_trading_post", "Build a trading post");
            add("craftorio.quest.build_trading_post.hint", "Craft a Construction Workbench (3 iron ingots, a crafting table, 5 planks) and open it. Build the trading post from its free blueprint.");
            add("craftorio.quest.first_sale", "Sell something");
            add("craftorio.quest.first_sale.hint", "Right-click the trading post with items, or feed it with hoppers and belts. Every item's value is shown in its tooltip.");
            add("craftorio.quest.build_burner_drill", "Build a burner drill");
            add("craftorio.quest.build_burner_drill.hint", "Build it at the workbench and place it on an ore field (iron, copper or coal): it mines the 3×3 blocks below it. Fuel it with coal.");
            add("craftorio.quest.build_conveyor_belt", "Build conveyor belts");
            add("craftorio.quest.build_conveyor_belt.hint", "The drill pushes its output out of its front. Lay belts from there to the trading post and your money comes in by itself.");
            add("craftorio.quest.sell_raw_iron", "Sell 64 raw iron");
            add("craftorio.quest.sell_raw_iron.hint", "Let a drill on an iron ore field deliver to the trading post. More drills on the same field mean more throughput.");
            add("craftorio.quest.build_inserter", "Build an inserter");
            add("craftorio.quest.build_inserter.hint", "Inserters move items from the block behind them to the block in front – from belts into machines, from chests onto belts.");
            add("craftorio.quest.unlock_coal_generator", "Buy the coal generator blueprint");
            add("craftorio.quest.unlock_coal_generator.hint", "Craft a terminal (iron, glass pane, redstone). In its Blueprints tab you buy new machines with credits.");
            add("craftorio.quest.unlock_power_pole", "Buy the power pole blueprint");
            add("craftorio.quest.unlock_power_pole.hint", "Power poles connect generators and machines within 2 blocks and link to each other up to 8 blocks apart.");
            add("craftorio.quest.unlock_electric_furnace", "Buy the electric furnace blueprint");
            add("craftorio.quest.unlock_electric_furnace.hint", "Smelted ingots are worth more than raw ore. Feed the furnace with an inserter and power it from a pole.");
            add("craftorio.quest.unlock_press", "Buy the press blueprint");
            add("craftorio.quest.unlock_press.hint", "The press turns ingots into plates and cables – every processing step raises the sale price.");
            add("craftorio.quest.sell_iron_plate", "Sell 100 iron plates");
            add("craftorio.quest.sell_iron_plate.hint", "Build a chain: drill → electric furnace → press → trading post.");
            add("craftorio.quest.earn_10k", "Earn 10.000 ¢ in total");
            add("craftorio.quest.earn_10k.hint", "Expand: more drills, more fields, more processing. The Statistics tab shows what earns the most.");
            add("craftorio.quest.build_crossbow_tower", "Build a crossbow tower");
            add("craftorio.quest.build_crossbow_tower.hint", "Buy the blueprint, build the tower and place it in your arena on open ground next to the path. Load it with bolts – or build an arena feeder in your factory that supplies bolts, cartridges and power.");
            add("craftorio.quest.td_1", "Complete tower defense level 1");
            add("craftorio.quest.td_1.hint", "Start the level in the terminal's Defense tab. Enemies only attack towers – your factory is never in danger. Every won level brings a new map: take your towers from the tower depot.");
            add("craftorio.quest.td_10", "Complete tower defense level 10");
            add("craftorio.quest.td_10.hint", "Level 10 rewards the drill core – the key to the tier 2 workbench. Upgrade and repair your towers between levels.");
            add("craftorio.quest.unlock_workbench_upgrade_2", "Upgrade to the assembly workbench");
            add("craftorio.quest.unlock_workbench_upgrade_2.hint", "Buy the upgrade kit with the drill core, build it and right-click your workbench with it.");
            add("craftorio.quest.unlock_assembler", "Buy the assembler blueprint");
            add("craftorio.quest.unlock_assembler.hint", "The assembler combines several parts into gears, circuits and motors – the most valuable goods of the surface.");
            add("craftorio.quest.sell_motor", "Sell 20 motors");
            add("craftorio.quest.sell_motor.hint", "Motors need gears, plates and cables: a small factory with several assemblers.");
            add("craftorio.quest.unlock_cave_entrance", "Buy the cave entrance blueprint");
            add("craftorio.quest.unlock_cave_entrance.hint", "Below the surface lies the sealed cave layer with new resources. An entrance is the only way in.");
            add("craftorio.quest.build_cave_entrance", "Build a cave entrance");
            add("craftorio.quest.build_cave_entrance.hint", "Place it on the surface, deliver cobblestone, plates, gears and motors, and power it with 40 FE/t. It drills a shaft and opens the caves.");
            add("craftorio.quest.sell_tin_ingot", "Sell 64 tin ingots");
            add("craftorio.quest.sell_tin_ingot.hint", "Tin, lead, sulfur, gold and quartz fields lie on the cave floor. Bring power down and set up drills there.");
            add("craftorio.quest.sell_battery", "Sell 32 batteries");
            add("craftorio.quest.sell_battery.hint", "Batteries are assembled from lead, sulfur and cables – a cave product worth far more than its parts.");
            add("craftorio.quest.unlock_elevator", "Buy the item elevator blueprint");
            add("craftorio.quest.unlock_elevator.hint", "Two elevators in the same column link through the rock: send cave goods up to your surface factory.");
            add("craftorio.quest.td_20", "Complete tower defense level 20");
            add("craftorio.quest.td_20.hint", "From level 20 crystal golems come – only energy towers (tesla, laser) hurt them fully.");
            add("craftorio.quest.td_30", "Complete tower defense level 30");
            add("craftorio.quest.td_30.hint", "Level 30 rewards the deep core – the key to the precision workbench (tier 3).");
            add("craftorio.quest.unlock_workbench_upgrade_3", "Upgrade to the precision workbench");
            add("craftorio.quest.unlock_workbench_upgrade_3.hint", "Buy the tier 3 upgrade kit with the deep core and apply it to your workbench.");
            add("craftorio.quest.unlock_mine_shaft", "Buy the mine shaft blueprint");
            add("craftorio.quest.unlock_mine_shaft.hint", "Build the mine shaft in an unlocked cave area: it drills through to the mine layer with diamonds, titanium, uranium and crystals.");
            add("craftorio.quest.sell_titanium_plate", "Sell 64 titanium plates");
            add("craftorio.quest.sell_titanium_plate.hint", "Smelt raw titanium, press the ingots. Deep drills (5×5) make the most of the mine fields.");
            add("craftorio.quest.sell_energy_crystal", "Sell 8 energy crystals");
            add("craftorio.quest.sell_energy_crystal.hint", "Energy crystals combine crystal shards, an advanced circuit and a battery – the most valuable good so far.");
            add("craftorio.quest.earn_1m", "Earn 1.000.000 ¢ in total");
            add("craftorio.quest.earn_1m.hint", "Scale up all three layers. Reactors burning fuel rods power the biggest factories.");
            add("craftorio.quest.td_40", "Complete tower defense level 40");
            add("craftorio.quest.td_40.hint", "The final challenge so far: laser towers and upgraded tesla towers against armoured waves.");
            add("craftorio.quest.next", "Next");
            add("craftorio.hud.guide", "Guide: %s");
            add("craftorio.hud.guide_done", "Guide: %s ✔ – collect in the terminal");
            add("craftorio.quest.claim", "Collect");
            add("craftorio.quest.done", "Done ✔");
            add("craftorio.quest.ready", "Reached!");
            add("craftorio.quest.open", "Not done yet");
            add("craftorio.quest.not_done", "This goal is not reached yet.");
            add("craftorio.quest.claimed", "Guide: %s – %s collected");
        }
    }

    public static final class German extends LanguageProvider {
        public German(PackOutput output) {
            super(output, Craftorio.MOD_ID, "de_de");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Deckgestein");
            add(ModBlocks.TRADING_POST.get(), "Handelsposten");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Eisenerzfeld");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Kupfererzfeld");
            add(ModBlocks.COAL_FIELD.get(), "Kohlefeld");
            add(ModBlocks.BURNER_DRILL.get(), "Brenner-Bohrer");
            add(ModBlocks.CONVEYOR_BELT.get(), "Förderband");
            add(ModBlocks.INSERTER.get(), "Greifarm");

            add(ModBlocks.COAL_GENERATOR.get(), "Kohle-Generator");
            add(ModBlocks.POWER_POLE.get(), "Strommast");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Elektro-Schmelzofen");
            add(ModBlocks.PRESS.get(), "Presse");
            add(ModBlocks.ASSEMBLER.get(), "Montagemaschine");
            add(ModItems.IRON_PLATE.get(), "Eisenplatte");
            add(ModItems.COPPER_CABLE.get(), "Kupferkabel");
            add(ModItems.IRON_GEAR.get(), "Zahnrad");
            add(ModItems.CIRCUIT.get(), "Schaltkreis");
            add(ModItems.MOTOR.get(), "Motor");

            add("craftorio.gui.energy", "Energie: %s / %s FE");
            add("craftorio.gui.no_recipe", "Rezept wählen");
            add("craftorio.power.no_network", "Nicht verbunden");
            add("craftorio.power.network", "Netz: %s Masten · %s Generatoren · %s Verbraucher · %s/%s FE/t · %s%% versorgt");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Konstruktionswerkbank");
            add(ModBlocks.ASSEMBLY_WORKBENCH.get(), "Montagewerkbank");
            add(ModBlocks.PRECISION_WORKBENCH.get(), "Präzisionswerkbank");
            add(ModItems.WORKBENCH_UPGRADE_2.get(), "Werkbank-Aufrüstsatz (Stufe 2)");
            add(ModItems.WORKBENCH_UPGRADE_3.get(), "Werkbank-Aufrüstsatz (Stufe 3)");
            add(ModItems.DRILL_CORE.get(), "Bohrkern");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonanzkristall");
            add(ModItems.DEEP_CORE.get(), "Tiefenkern");
            add(ModItems.STAR_SHARD.get(), "Sternenerz-Splitter");

            add("craftorio.key_material.hint", "Schlüsselmaterial – Belohnung für Tower-Defense-Level %s");
            add("craftorio.workbench.upgrade_hint", "Rechtsklick auf eine Werkbank der Stufe %s rüstet sie auf");
            add("craftorio.workbench.upgrade_target", "Funktioniert nur an einer Werkbank der Stufe %s");
            add("craftorio.workbench.hint", "Klick: 1 bauen · Shift-Klick: 10 bauen");
            add("craftorio.workbench.build", "Bauen");
            add("craftorio.workbench.locked", "Gesperrt");
            add("craftorio.workbench.needs_tier", "Braucht Werkbank Stufe %s");
            add("craftorio.workbench.tier_too_low", "Dieser Bauplan braucht eine Werkbank der Stufe %s");
            add("craftorio.workbench.missing", "Material fehlt");
            add("craftorio.terminal.tab.blueprints", "Baupläne");
            add("craftorio.terminal.tab.stats", "Statistik");
            add("craftorio.terminal.unlock", "Kaufen");
            add("craftorio.terminal.stats.earned", "Gesamt eingenommen");
            add("craftorio.terminal.stats.spent", "Gesamt ausgegeben");
            add("craftorio.terminal.stats.recent", "Eingenommen in den letzten 10 Minuten");
            add("craftorio.terminal.stats.top", "Meistverkauft");
            add("craftorio.blueprint.tier", "Stufe %s");
            add("craftorio.blueprint.requires", "braucht %s");
            add("craftorio.blueprint.materials", "Material:");
            add("craftorio.blueprint.unlock_items", "Freischalten braucht zusätzlich:");
            add("craftorio.blueprint.unlocked", "Bauplan %s für %s freigeschaltet");
            add("craftorio.blueprint.locked", "Dieser Bauplan ist noch nicht freigeschaltet");
            add("craftorio.blueprint.status.unlocked", "freigeschaltet");
            add("craftorio.blueprint.status.available", "verfügbar");
            add("craftorio.blueprint.status.missing_prerequisite", "Erst die Voraussetzung freischalten");
            add("craftorio.blueprint.status.missing_key_items", "braucht Schlüsselmaterial");
            add("craftorio.blueprint.status.not_enough_credits", "zu wenig Credits");

            add(ModBlocks.ZONE_CORE.get(), "Zonenkern");
            add(ModBlocks.ENEMY_PORTAL.get(), "Feindportal");
            add(ModBlocks.PATH_BLOCK.get(), "Pfadblock");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Armbrustturm");
            add(ModBlocks.GUN_TURRET.get(), "Geschützturm");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla-Turm");
            add(ModBlocks.TOWER_RUIN.get(), "Turmruine");
            add(ModItems.BOLT.get(), "Bolzen");
            add(ModItems.CARTRIDGE.get(), "Patrone");
            add("entity.craftorio.crawler", "Krabbler");
            add("entity.craftorio.breaker", "Brecher");
            add("entity.craftorio.spitter", "Spucker");
            add("entity.craftorio.brood_mother", "Brutmutter");

            add("craftorio.terminal.tab.defense", "Abwehr");
            add("craftorio.hud.td", "Level %s · Welle %s/%s · Leben %s/%s · %s Gegner");
            add("craftorio.td.next_level", "Nächstes Level");
            add("craftorio.td.wave", "Welle");
            add("craftorio.td.lives", "Leben");
            add("craftorio.td.enemies", "Verbleibende Gegner");
            add("craftorio.td.reward", "Belohnung");
            add("craftorio.td.milestone", "Nächstes Schlüsselmaterial");
            add("craftorio.td.milestone.in", "in %s Leveln");
            add("craftorio.td.key_next", "Dieses Level bringt ein Schlüsselmaterial!");
            add("craftorio.td.rules", "Ein Level ist verloren, wenn %s Leben weg sind. Gegner greifen nur Türme an – die Fabrik bleibt sicher. Zerstörte Türme hinterlassen Ruinen, die du wieder aufbauen kannst.");
            add("craftorio.td.button.start", "Level %s starten");
            add("craftorio.td.button.auto_on", "Automatisch weiter: an");
            add("craftorio.td.button.auto_off", "Automatisch weiter: aus");
            add("craftorio.td.button.repair", "Alle Türme reparieren (%s)");
            add("craftorio.td.started", "Level %s gestartet!");
            add("craftorio.td.won", "Level %s geschafft! +%s");
            add("craftorio.td.lost", "Level %s verloren – repariere oder verbessere deine Türme und versuche es erneut.");
            add("craftorio.td.repair.nothing", "Nichts zu reparieren.");
            add("craftorio.td.repair.too_expensive", "Zu wenig Credits (%s nötig).");
            add("craftorio.td.repair.done", "Türme für %s repariert.");
            add("craftorio.td.error.no_zone", "Dein Team hat keine Verteidigungszone.");
            add("craftorio.td.error.running", "Es läuft bereits ein Level.");
            add("craftorio.td.error.no_portal", "In der Zone steht kein Feindportal.");
            add("craftorio.td.error.no_team", "Du bist in keinem Team.");
            add("craftorio.td.error.zone_exists", "Dein Team hat bereits einen Zonenkern.");
            add("craftorio.td.error.overworld_only", "Verteidigungszonen gibt es nur in der Oberwelt.");
            add("craftorio.td.error.outside_zone", "Nur innerhalb deiner Verteidigungszone (%s Blöcke um den Zonenkern).");
            add("craftorio.td.error.foreign_zone", "Dieser Zonenkern gehört einem anderen Team.");
            add("craftorio.td.error.path.no_start", "Neben dem Feindportal liegt kein Pfadblock.");
            add("craftorio.td.error.path.branch", "Der Pfad verzweigt sich – er muss eine einzige Linie sein.");
            add("craftorio.td.error.path.dead_end", "Der Pfad endet, bevor er den Zonenkern erreicht.");
            add("craftorio.td.error.path.too_short", "Der Pfad ist zu kurz (mindestens %s Blöcke).");
            add("craftorio.td.error.path.too_long", "Der Pfad ist zu lang.");
            add("craftorio.tower.upgrade", "Aufrüsten");
            add("craftorio.tower.level", "Stufe %s");
            add("craftorio.tower.upgraded", "Turm auf Stufe %s aufgerüstet für %s");
            add("craftorio.tower.rebuilt", "Turm für %s wieder aufgebaut");

            add(ModBlocks.CAVE_RUBBLE.get(), "Höhlengeröll");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Höhleneingang");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Zinnerzfeld");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Bleierzfeld");
            add(ModBlocks.SULFUR_FIELD.get(), "Schwefelfeld");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Golderzfeld");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quarzfeld");
            add(ModItems.RAW_TIN.get(), "Rohzinn");
            add(ModItems.TIN_INGOT.get(), "Zinnbarren");
            add(ModItems.RAW_LEAD.get(), "Rohblei");
            add(ModItems.LEAD_INGOT.get(), "Bleibarren");
            add(ModItems.SULFUR.get(), "Schwefel");
            add(ModItems.BATTERY.get(), "Batterie");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Fortgeschrittener Schaltkreis");
            add(ModBlocks.ELEVATOR.get(), "Warenaufzug");
            add("craftorio.elevator.mode.receive", "Modus: empfangen (Ausgabe nach vorne)");
            add("craftorio.elevator.mode.send_up", "Modus: nach oben senden");
            add("craftorio.elevator.mode.send_down", "Modus: nach unten senden");
            add("craftorio.elevator.target", "→ Gegenstück %s Blöcke entfernt");
            add("craftorio.elevator.no_target", "→ kein Aufzug in dieser Spalte!");
            add("craftorio.cave.needs", "Baustelle braucht noch:");
            add("craftorio.cave.drilling", "Bohrung: %s%% (braucht %s FE/t über einen Strommast)");
            add("craftorio.cave.open", "Höhleneingang offen – über das Gerüst hinab (Schleichen zum Absteigen).");
            add("craftorio.cave.opened", "Ein Höhleneingang wurde geöffnet! Der Höhlenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.cave.error.overworld_only", "Höhleneingänge gibt es nur in der Oberwelt.");
            add("craftorio.cave.error.too_deep", "Höhleneingänge an der Oberfläche bauen (ab Y 50).");
            add("craftorio.cave.error.no_layer", "Unter dieser Stelle gibt es keine Höhlenschicht (Gebiet vor dem Höhlen-Update erzeugt).");

            add("craftorio.drill.status", "Bohrer: %s/%s Feldblöcke · %s Items/s · Brennstoff für %s s");
            add("craftorio.drill.overlap", "Zu nah an einem anderen Bohrer – Abbauflächen dürfen sich nicht überlappen.");
            add(ModBlocks.MINE_RUBBLE.get(), "Minengeröll");
            add(ModBlocks.MINE_SHAFT.get(), "Minenschacht");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamantfeld");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanerzfeld");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranerzfeld");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Kristallfeld");
            add(ModItems.RAW_TITANIUM.get(), "Roh-Titan");
            add(ModItems.TITANIUM_INGOT.get(), "Titanbarren");
            add(ModItems.TITANIUM_PLATE.get(), "Titanplatte");
            add(ModItems.RAW_URANIUM.get(), "Roh-Uran");
            add(ModItems.URANIUM_PELLET.get(), "Uranpellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Kristallsplitter");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energiekristall");
            add(ModItems.FUEL_ROD.get(), "Brennstab");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Elektrischer Bohrer");
            add(ModBlocks.DEEP_DRILL.get(), "Tiefenbohrer");
            add(ModBlocks.FAST_BELT.get(), "Schnelles Förderband");
            add(ModBlocks.EXPRESS_BELT.get(), "Express-Förderband");
            add(ModBlocks.REACTOR.get(), "Reaktor");
            add(ModBlocks.LASER_TOWER.get(), "Laserturm");
            add("entity.craftorio.crystal_golem", "Kristallgolem");
            add("craftorio.command.layer_unlocked", "%s Chunks der Schicht freigeschaltet (Y %s bis %s); sie werden ausgehöhlt.");
            add("craftorio.mine.open", "Minenschacht offen – über das Gerüst hinab in die Minenschicht.");
            add("craftorio.mine.opened", "Ein Minenschacht wurde geöffnet! Der Minenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.mine.error.not_in_caves", "Minenschächte in einem freigeschalteten Bereich der Höhlenschicht bauen (Y 0 bis 39).");
            add("craftorio.drill.status_electric", "Bohrer: %s/%s Feldblöcke · %s Items/s · %s FE gespeichert (braucht %s FE/t)");

            add("craftorio.tooltip.sell_price", "Verkaufswert: %s");
            add("craftorio.tooltip.sell_price_stack", "Verkaufswert: %s (Stapel: %s)");
            add("craftorio.trading_post.sold", "Verkauft für %s");
            add("craftorio.trading_post.info", "Handelsposten von Team %s – bisher eingenommen: %s");

            add("craftorio.command.credits", "Team %s hat %s");
            add("craftorio.command.team.info", "Team %s – Kontostand: %s – Mitglieder: %s");
            add("craftorio.command.team.list_entry", "%s (%s Mitglieder)");
            add("craftorio.command.team.created", "Team %s gegründet.");
            add("craftorio.command.team.invited", "%s hat dich in Team %s eingeladen.");
            add("craftorio.command.team.invite_sent", "Einladung an %s gesendet.");
            add("craftorio.command.team.joined", "Du bist Team %s beigetreten.");
            add("craftorio.command.team.left", "Du hast dein Team verlassen und spielst jetzt als Team %s.");

            add("craftorio.team.error.name_taken", "Ein Team namens %s existiert bereits.");
            add("craftorio.team.error.invalid_name", "Teamnamen müssen 1–%s Zeichen lang sein: Buchstaben, Ziffern, Leerzeichen, _ und -.");
            add("craftorio.team.error.no_team", "Du bist in keinem Team.");
            add("craftorio.team.error.already_member", "Dieser Spieler ist bereits in diesem Team.");
            add("craftorio.team.error.unknown_team", "Es gibt kein Team namens %s.");
            add("craftorio.team.error.not_invited", "Du wurdest nicht in Team %s eingeladen.");
            add("craftorio.team.error.alone", "Du bist das einzige Mitglied deines Teams.");
            add("craftorio.command.team.rights", "Leitung: %s – Ausgaben: %s");
            add("craftorio.command.team.spending.all", "alle Mitglieder");
            add("craftorio.command.team.spending.leader", "nur Leitung");
            add("craftorio.command.team.spending.set_all", "Alle Mitglieder dürfen jetzt Credits des Teams ausgeben.");
            add("craftorio.command.team.spending.set_leader", "Nur noch die Teamleitung darf Credits ausgeben.");
            add("craftorio.command.team.kicked", "%s wurde aus dem Team entfernt.");
            add("craftorio.command.team.kicked_you", "Du wurdest aus Team %s entfernt und spielst jetzt in deinem eigenen Team.");
            add("craftorio.command.team.new_leader", "%s leitet jetzt das Team.");
            add("craftorio.team.error.not_leader", "Das darf nur die Teamleitung.");
            add("craftorio.team.error.not_member", "Dieser Spieler ist nicht in deinem Team.");
            add("craftorio.team.error.kick_self", "Du kannst dich nicht selbst entfernen – nutze /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Nur deine Teamleitung darf Credits ausgeben.");
            add("craftorio.team.error.one_player", "Gib genau einen Spieler an.");
            add("craftorio.protection.denied", "Das gehört Team %s.");
            add("craftorio.protection.too_close", "Zu nah an Team %s – halte einen Block Abstand zu deren Maschinen und Behältern.");
            add("emi.category.craftorio.pressing", "Pressen");
            add("emi.category.craftorio.assembling", "Montage");
            add("emi.category.craftorio.blueprint", "Bauplan (Werkbank)");
            add("craftorio.emi.time", "%s s");
            add("craftorio.emi.free", "kostenlos");
            add("config.jade.plugin_craftorio.status", "Craftorio-Status");
            add("config.jade.plugin_craftorio.ore_field", "Craftorio-Erzfelder");
            add("craftorio.jade.owner", "Besitzer: Team %s");
            add("craftorio.jade.progress", "Fortschritt: %s%%");
            add("craftorio.jade.tower", "HP %s / %s · Stufe %s");
            add("craftorio.jade.ammo", "Munition: %s");
            add("craftorio.jade.ruin", "Zerstört – Wiederaufbau für %s");
            add("craftorio.jade.ore_field", "Liefert %s (je %s) – unerschöpflich");
            add("craftorio.terminal.tab.quests", "Leitfaden");
            add(ModItems.GUIDE_BOOK.get(), "Craftorio-Handbuch");
            add("key.craftorio.guide", "Handbuch öffnen");
            add("key.categories.craftorio", "Craftorio");
            add("craftorio.guide.current", "Aktuell");
            add("craftorio.guide.step", "Leitfaden · Schritt %s von %s");
            add("craftorio.guide.progress", "Fortschritt: %s");
            add("craftorio.guide.reward", "Belohnung: %s");
            add("craftorio.guide.buy_in_terminal", "Bauplan im Terminal kaufen (%s), dann an einer Werkbank bauen:");
            add("craftorio.guide.build_at", "Bauen an der %s aus:");
            add("craftorio.guide.key", "Schlüssel:");
            add("craftorio.guide.crafting", "Rezept: %s");
            add("craftorio.guide.vanilla_table", "(normale Werkbank)");
            add("craftorio.guide.upgrade_bench", "Braucht eine Werkbank der Stufe %s: Aufrüstsatz im Terminal kaufen und die Werkbank damit rechtsklicken.");
            add("craftorio.guide.value", "Verkaufswert: %s pro Stück");
            add("craftorio.guide.mined_from", "Abbau am %s – per Bohrer oder von Hand");
            add("craftorio.guide.made_in", "Hergestellt in der %s aus:");
            add("craftorio.guide.smelted", "Geschmolzen im Ofen oder Elektroofen:");
            add("craftorio.guide.earn", "Verkaufe verarbeitete Waren: je mehr Verarbeitungsschritte, desto höher der Preis. Die Statistik im Terminal zeigt, was sich am meisten lohnt.");
            add("craftorio.guide.defense", "Tower Defense: geh durch dein Arena-Tor, lege mit dem Pfadstab einen Weg vom offenen Tor zum Kern, stelle Türme daneben und starte das Level im Terminal (Tab Abwehr).");
            add("craftorio.hud.guide_key", "[%s] Handbuch");
            add("craftorio.arena.error.overworld_only", "Arena-Tore funktionieren nur in der Oberwelt.");
            add("craftorio.arena.error.not_arena", "Nur in deiner Arena.");
            add("craftorio.arena.error.outside_field", "Nur innerhalb des Arenafelds.");
            add("craftorio.arena.error.foreign", "Das ist die Arena eines anderen Teams.");
            add("craftorio.arena.error.no_tower_here", "Türme stehen nur auf freiem Boden oder auf einem Plateau – nicht auf dem Weg, Bäumen, Fels, Wasser oder Lava.");
            add("craftorio.arena.error.no_building", "Die Arena lässt sich nicht verändern – lege den Weg mit dem Pfadstab und stelle Türme auf.");
            add("craftorio.arena.path.blocked", "Dort kann der Weg nicht entlangführen.");
            add("craftorio.arena.path_wand.tooltip", "Klick auf den Arenaboden legt Weg; der nächste Klick in derselben Reihe oder Spalte zieht eine gerade Linie. Schleichen + Klick entfernt Weg oder beginnt eine neue Linie.");
            add("craftorio.arena.welcome", "Arena · Level %s · Karte: %s – %s");
            add("craftorio.arena.new_map", "Die Arena hat sich verändert: neue Karte %s. Deine Türme warten im Turmdepot – lege einen neuen Weg!");
            add("craftorio.arena.old_core", "Verteidigungszonen sind jetzt Arenen – baue ein Arena-Tor (Gratis-Bauplan) und geh hindurch.");
            add("craftorio.arena.theme.forest", "Wald");
            add("craftorio.arena.theme.forest.rule", "Gegner im Dickicht sind getarnt: Türme erkennen sie nur auf halbe Reichweite.");
            add("craftorio.arena.theme.mountain", "Berge");
            add("craftorio.arena.theme.mountain.rule", "Türme auf Plateaus reichen 30 % weiter; Geröll bremst Gegner.");
            add("craftorio.arena.theme.fire", "Feuer");
            add("craftorio.arena.theme.fire.rule", "Lavaschlote brechen alle paar Sekunden aus und verbrennen Gegner, die darüber laufen.");
            add("craftorio.arena.theme.water", "Wasser");
            add("craftorio.arena.theme.water.rule", "Der Fluss ist nur an Furten passierbar; Flachwasser bremst Gegner stark.");
            add("craftorio.arena.theme.colosseum", "Kolosseum");
            add("craftorio.arena.theme.colosseum.rule", "Boss-Level: offener Sand zwischen Säulen.");
            add("craftorio.arena.mutator.fog", "Mutator Nebel: Türme sehen 25 % weniger weit (+25 % Belohnung).");
            add("craftorio.arena.mutator.haste", "Mutator Eilmarsch: Gegner sind 30 % schneller (+25 % Belohnung).");
            add("craftorio.arena.mutator.hardened", "Mutator Gehärtet: Gegner haben 35 % mehr Leben (+30 % Belohnung).");
            add("craftorio.arena.depot.empty", "Das Turmdepot ist leer.");
            add("craftorio.arena.depot.taken", "%s Stapel aus dem Turmdepot genommen.");
            add("craftorio.arena.feeder.status", "Arena-Vorrat: %s / %s FE · %s Bolzen · %s Patronen");
            add("craftorio.arena.feeder.no_owner", "Dieser Einspeiser gehört keinem Team.");
            add("craftorio.arena.feeder.no_arena", "Dein Team hat noch keine Arena – geh zuerst durch ein Arena-Tor.");
            add("craftorio.td.error.not_running", "Es läuft kein Level.");
            add("craftorio.td.call.not_now", "Die nächste Welle lässt sich nur zwischen zwei Wellen rufen.");
            add("craftorio.td.call.done", "Nächste Welle früher gerufen! +%s");
            add("craftorio.td.won_stars", "Level %s geschafft %s! +%s");
            add("craftorio.td.button.call", "Welle rufen");
            add("craftorio.td.map", "Karte");
            add("craftorio.td.last_stars", "Letztes Level");
            add("craftorio.td.preview", "Nächste Welle:");
            add("craftorio.td.reserves", "Arena-Vorrat: %s FE · %s Bolzen · %s Patronen");
            add("craftorio.tower.target.first", "Ziel: Erster");
            add("craftorio.tower.target.last", "Ziel: Letzter");
            add("craftorio.tower.target.strongest", "Ziel: Stärkster");
            add("craftorio.tower.target.weakest", "Ziel: Schwächster");
            add("craftorio.quest.build_arena_gate", "Baue ein Arena-Tor");
            add("craftorio.quest.build_arena_gate.hint", "Baue das Arena-Tor (Gratis-Bauplan), stelle es auf und rechtsklicke es: es bringt dich in deine eigene Arena. Lege dort mit dem Pfadstab einen Weg vom offenen Tor in der Westmauer zum Kern in der Ostmauer.");
            add("craftorio.td.help", "Noch keine Arena. Baue ein Arena-Tor (Gratis-Bauplan), stelle es in der Oberwelt auf und rechtsklicke es. Lege in deiner Arena mit dem Pfadstab einen Weg vom offenen Gegnertor zum Kern und stelle Türme auf freien Boden. Jedes geschaffte Level bringt eine neue Karte.");
            add("craftorio.td.key_reward", "Schlüsselmaterial %s wartet im Turmdepot!");
            add("craftorio.td.path_ok", "Weg OK: %s Blöcke vom Tor bis zum Kern.");
            add(ModBlocks.ARENA_BASE.get(), "Arenaboden");
            add(ModBlocks.ARENA_CLIFF.get(), "Plateaufels");
            add(ModBlocks.ARENA_GATE.get(), "Arena-Tor");
            add(ModBlocks.ARENA_EXIT.get(), "Arena-Ausgang");
            add(ModBlocks.TOWER_DEPOT.get(), "Turmdepot");
            add(ModBlocks.ARENA_FEEDER.get(), "Arena-Einspeiser");
            add(ModItems.PATH_WAND.get(), "Pfadstab");
            add("craftorio.quest.build_trading_post", "Baue einen Handelsposten");
            add("craftorio.quest.build_trading_post.hint", "Stelle eine Konstruktionswerkbank her (3 Eisenbarren, Werkbank, 5 Bretter) und öffne sie. Baue dort den Handelsposten aus seinem kostenlosen Bauplan.");
            add("craftorio.quest.first_sale", "Verkaufe etwas");
            add("craftorio.quest.first_sale.hint", "Rechtsklicke den Handelsposten mit Items oder beliefere ihn per Trichter oder Band. Den Wert jedes Items zeigt sein Tooltip.");
            add("craftorio.quest.build_burner_drill", "Baue einen Brenner-Bohrer");
            add("craftorio.quest.build_burner_drill.hint", "Baue ihn an der Werkbank und setze ihn auf ein Erzfeld (Eisen, Kupfer oder Kohle): er baut die 3×3 Blöcke darunter ab. Befeuere ihn mit Kohle.");
            add("craftorio.quest.build_conveyor_belt", "Baue Förderbänder");
            add("craftorio.quest.build_conveyor_belt.hint", "Der Bohrer gibt nach vorne aus. Lege Bänder von dort zum Handelsposten – dann verdienst du automatisch.");
            add("craftorio.quest.sell_raw_iron", "Verkaufe 64 Roheisen");
            add("craftorio.quest.sell_raw_iron.hint", "Lass einen Bohrer auf einem Eisenerzfeld zum Handelsposten liefern. Mehr Bohrer auf dem Feld bedeuten mehr Durchsatz.");
            add("craftorio.quest.build_inserter", "Baue einen Greifarm");
            add("craftorio.quest.build_inserter.hint", "Greifarme bewegen Items vom Block hinter ihnen zum Block davor – vom Band in Maschinen, aus Kisten aufs Band.");
            add("craftorio.quest.unlock_coal_generator", "Kaufe den Bauplan Kohlegenerator");
            add("craftorio.quest.unlock_coal_generator.hint", "Stelle ein Terminal her (Eisen, Glasscheibe, Redstone). Im Tab Baupläne kaufst du neue Maschinen mit Credits.");
            add("craftorio.quest.unlock_power_pole", "Kaufe den Bauplan Strommast");
            add("craftorio.quest.unlock_power_pole.hint", "Strommasten verbinden Generatoren und Maschinen im Umkreis von 2 Blöcken und untereinander bis 8 Blöcke weit.");
            add("craftorio.quest.unlock_electric_furnace", "Kaufe den Bauplan Elektroofen");
            add("craftorio.quest.unlock_electric_furnace.hint", "Barren sind mehr wert als Roherz. Beliefere den Ofen per Greifarm und versorge ihn über einen Strommast.");
            add("craftorio.quest.unlock_press", "Kaufe den Bauplan Presse");
            add("craftorio.quest.unlock_press.hint", "Die Presse macht aus Barren Platten und Kabel – jede Verarbeitungsstufe steigert den Verkaufspreis.");
            add("craftorio.quest.sell_iron_plate", "Verkaufe 100 Eisenplatten");
            add("craftorio.quest.sell_iron_plate.hint", "Baue eine Kette: Bohrer → Elektroofen → Presse → Handelsposten.");
            add("craftorio.quest.earn_10k", "Verdiene insgesamt 10.000 ¢");
            add("craftorio.quest.earn_10k.hint", "Erweitere: mehr Bohrer, mehr Felder, mehr Verarbeitung. Der Tab Statistik zeigt, was am meisten einbringt.");
            add("craftorio.quest.build_crossbow_tower", "Baue einen Armbrustturm");
            add("craftorio.quest.build_crossbow_tower.hint", "Kaufe den Bauplan, baue den Turm und stelle ihn in deiner Arena auf freien Boden neben den Weg. Lade ihn mit Bolzen – oder baue in deiner Fabrik einen Arena-Einspeiser, der Bolzen, Patronen und Strom liefert.");
            add("craftorio.quest.td_1", "Schaffe Tower-Defense-Level 1");
            add("craftorio.quest.td_1.hint", "Starte das Level im Terminal-Tab Abwehr. Gegner greifen nur Türme an – deine Fabrik ist nie in Gefahr. Jedes geschaffte Level bringt eine neue Karte: hol deine Türme aus dem Turmdepot.");
            add("craftorio.quest.td_10", "Schaffe Tower-Defense-Level 10");
            add("craftorio.quest.td_10.hint", "Level 10 belohnt mit dem Bohrkern – dem Schlüssel zur Werkbank der Stufe 2. Rüste Türme zwischen den Levels auf und repariere sie.");
            add("craftorio.quest.unlock_workbench_upgrade_2", "Rüste auf die Montagewerkbank auf");
            add("craftorio.quest.unlock_workbench_upgrade_2.hint", "Kaufe den Aufrüstsatz mit dem Bohrkern, baue ihn und rechtsklicke damit deine Werkbank.");
            add("craftorio.quest.unlock_assembler", "Kaufe den Bauplan Montagemaschine");
            add("craftorio.quest.unlock_assembler.hint", "Die Montagemaschine kombiniert Teile zu Zahnrädern, Schaltkreisen und Motoren – den wertvollsten Waren der Oberfläche.");
            add("craftorio.quest.sell_motor", "Verkaufe 20 Motoren");
            add("craftorio.quest.sell_motor.hint", "Motoren brauchen Zahnräder, Platten und Kabel: eine kleine Fabrik mit mehreren Montagemaschinen.");
            add("craftorio.quest.unlock_cave_entrance", "Kaufe den Bauplan Höhleneingang");
            add("craftorio.quest.unlock_cave_entrance.hint", "Unter der Oberfläche liegt die versiegelte Höhlenschicht mit neuen Rohstoffen. Ein Eingang ist der einzige Weg hinein.");
            add("craftorio.quest.build_cave_entrance", "Baue einen Höhleneingang");
            add("craftorio.quest.build_cave_entrance.hint", "Setze ihn an die Oberfläche, liefere Bruchstein, Platten, Zahnräder und Motoren und versorge ihn mit 40 FE/t. Er bohrt einen Schacht und öffnet die Höhlen.");
            add("craftorio.quest.sell_tin_ingot", "Verkaufe 64 Zinnbarren");
            add("craftorio.quest.sell_tin_ingot.hint", "Zinn-, Blei-, Schwefel-, Gold- und Quarzfelder liegen auf dem Höhlenboden. Bring Strom nach unten und baue dort Bohrer auf.");
            add("craftorio.quest.sell_battery", "Verkaufe 32 Batterien");
            add("craftorio.quest.sell_battery.hint", "Batterien entstehen aus Blei, Schwefel und Kabeln – ein Höhlenprodukt, viel mehr wert als seine Teile.");
            add("craftorio.quest.unlock_elevator", "Kaufe den Bauplan Warenaufzug");
            add("craftorio.quest.unlock_elevator.hint", "Zwei Aufzüge in derselben Spalte verbinden sich durch den Fels: schicke Höhlenwaren hoch zu deiner Fabrik.");
            add("craftorio.quest.td_20", "Schaffe Tower-Defense-Level 20");
            add("craftorio.quest.td_20.hint", "Ab Level 20 kommen Kristallgolems – nur Energietürme (Tesla, Laser) schaden ihnen voll.");
            add("craftorio.quest.td_30", "Schaffe Tower-Defense-Level 30");
            add("craftorio.quest.td_30.hint", "Level 30 belohnt mit dem Tiefenkern – dem Schlüssel zur Präzisionswerkbank (Stufe 3).");
            add("craftorio.quest.unlock_workbench_upgrade_3", "Rüste auf die Präzisionswerkbank auf");
            add("craftorio.quest.unlock_workbench_upgrade_3.hint", "Kaufe den Aufrüstsatz der Stufe 3 mit dem Tiefenkern und wende ihn auf deine Werkbank an.");
            add("craftorio.quest.unlock_mine_shaft", "Kaufe den Bauplan Minenschacht");
            add("craftorio.quest.unlock_mine_shaft.hint", "Baue den Minenschacht in einem freigeschalteten Höhlenbereich: er bohrt bis in die Minenschicht mit Diamant, Titan, Uran und Kristallen.");
            add("craftorio.quest.sell_titanium_plate", "Verkaufe 64 Titanplatten");
            add("craftorio.quest.sell_titanium_plate.hint", "Schmelze Roh-Titan und presse die Barren. Tiefenbohrer (5×5) holen am meisten aus den Minenfeldern.");
            add("craftorio.quest.sell_energy_crystal", "Verkaufe 8 Energiekristalle");
            add("craftorio.quest.sell_energy_crystal.hint", "Energiekristalle vereinen Kristallsplitter, einen fortgeschrittenen Schaltkreis und eine Batterie – die bisher wertvollste Ware.");
            add("craftorio.quest.earn_1m", "Verdiene insgesamt 1.000.000 ¢");
            add("craftorio.quest.earn_1m.hint", "Baue alle drei Schichten aus. Reaktoren mit Brennstäben versorgen die größten Fabriken.");
            add("craftorio.quest.td_40", "Schaffe Tower-Defense-Level 40");
            add("craftorio.quest.td_40.hint", "Die bisher letzte Herausforderung: Lasertürme und aufgerüstete Tesla-Türme gegen gepanzerte Wellen.");
            add("craftorio.quest.next", "Als Nächstes");
            add("craftorio.hud.guide", "Leitfaden: %s");
            add("craftorio.hud.guide_done", "Leitfaden: %s ✔ – im Terminal abholen");
            add("craftorio.quest.claim", "Abholen");
            add("craftorio.quest.done", "Erledigt ✔");
            add("craftorio.quest.ready", "Erreicht!");
            add("craftorio.quest.open", "Noch offen");
            add("craftorio.quest.not_done", "Dieses Ziel ist noch nicht erreicht.");
            add("craftorio.quest.claimed", "Leitfaden: %s – %s erhalten");
        }
    }
}
