package de.craftorio.datagen;

import de.craftorio.Craftorio;
import de.craftorio.registry.ModBlocks;
import de.craftorio.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public final class ModLanguageProvider {
    private ModLanguageProvider() {
    }

    public static final class English extends LanguageProvider {
        public English(PackOutput output) {
            super(output, Craftorio.MOD_ID, "en_us");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Cap Rock");
            add(ModBlocks.TRADING_POST.get(), "Trading Post");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Iron Ore Field");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Copper Ore Field");
            add(ModBlocks.COAL_FIELD.get(), "Coal Field");
            add(ModBlocks.BURNER_DRILL.get(), "Burner Drill");
            add(ModBlocks.CONVEYOR_BELT.get(), "Conveyor Belt");
            add(ModBlocks.INSERTER.get(), "Inserter");

            add(ModBlocks.COAL_GENERATOR.get(), "Coal Generator");
            add(ModBlocks.POWER_POLE.get(), "Power Pole");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Electric Furnace");
            add(ModBlocks.PRESS.get(), "Press");
            add(ModBlocks.ASSEMBLER.get(), "Assembler");
            add(ModItems.IRON_PLATE.get(), "Iron Plate");
            add(ModItems.COPPER_CABLE.get(), "Copper Cable");
            add(ModItems.IRON_GEAR.get(), "Iron Gear");
            add(ModItems.CIRCUIT.get(), "Circuit");
            add(ModItems.MOTOR.get(), "Motor");

            add("craftorio.gui.energy", "Energy: %s / %s FE");
            add("craftorio.gui.no_recipe", "Choose a recipe");
            add("craftorio.power.no_network", "Not connected");
            add("craftorio.power.network", "Grid: %s poles · %s generators · %s consumers · %s/%s FE/t · %s%% supplied");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Construction Workbench");
            add(ModBlocks.ASSEMBLY_WORKBENCH.get(), "Assembly Workbench");
            add(ModBlocks.PRECISION_WORKBENCH.get(), "Precision Workbench");
            add(ModItems.WORKBENCH_UPGRADE_2.get(), "Workbench Upgrade Kit (Tier 2)");
            add(ModItems.WORKBENCH_UPGRADE_3.get(), "Workbench Upgrade Kit (Tier 3)");
            add(ModItems.DRILL_CORE.get(), "Drill Core");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonance Crystal");
            add(ModItems.DEEP_CORE.get(), "Deep Core");
            add(ModItems.STAR_SHARD.get(), "Star Shard");

            add("craftorio.key_material.hint", "Key material – reward for tower defense level %s");
            add("craftorio.workbench.upgrade_hint", "Right-click a tier %s workbench to upgrade it");
            add("craftorio.workbench.upgrade_target", "Only works on a tier %s workbench");
            add("craftorio.workbench.hint", "Click: build 1 · Shift-click: build 10");
            add("craftorio.workbench.build", "Build");
            add("craftorio.workbench.locked", "Locked");
            add("craftorio.workbench.needs_tier", "Needs workbench tier %s");
            add("craftorio.workbench.tier_too_low", "This blueprint needs a tier %s workbench");
            add("craftorio.workbench.missing", "Missing materials");
            add("craftorio.terminal.tab.blueprints", "Blueprints");
            add("craftorio.terminal.tab.stats", "Statistics");
            add("craftorio.terminal.unlock", "Unlock");
            add("craftorio.terminal.stats.earned", "Total earned");
            add("craftorio.terminal.stats.spent", "Total spent");
            add("craftorio.terminal.stats.recent", "Earned in the last 10 minutes");
            add("craftorio.terminal.stats.top", "Best sellers");
            add("craftorio.blueprint.tier", "Tier %s");
            add("craftorio.blueprint.requires", "needs %s");
            add("craftorio.blueprint.materials", "Materials:");
            add("craftorio.blueprint.unlock_items", "Unlock also needs:");
            add("craftorio.blueprint.unlocked", "Blueprint %s unlocked for %s");
            add("craftorio.blueprint.locked", "This blueprint is not unlocked yet");
            add("craftorio.blueprint.status.unlocked", "unlocked");
            add("craftorio.blueprint.status.available", "available");
            add("craftorio.blueprint.status.missing_prerequisite", "Unlock the prerequisite first");
            add("craftorio.blueprint.status.missing_key_items", "needs key material");
            add("craftorio.blueprint.status.not_enough_credits", "not enough credits");

            add(ModBlocks.ZONE_CORE.get(), "Zone Core");
            add(ModBlocks.ENEMY_PORTAL.get(), "Enemy Portal");
            add(ModBlocks.PATH_BLOCK.get(), "Path Block");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Crossbow Tower");
            add(ModBlocks.GUN_TURRET.get(), "Gun Turret");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla Tower");
            add(ModBlocks.TOWER_RUIN.get(), "Tower Ruin");
            add(ModItems.BOLT.get(), "Bolt");
            add(ModItems.CARTRIDGE.get(), "Cartridge");
            add("entity.craftorio.crawler", "Crawler");
            add("entity.craftorio.breaker", "Breaker");
            add("entity.craftorio.spitter", "Spitter");
            add("entity.craftorio.brood_mother", "Brood Mother");

            add("craftorio.terminal.tab.defense", "Defense");
            add("craftorio.hud.td", "Level %s · wave %s/%s · lives %s/%s · %s enemies");
            add("craftorio.td.help", "No defense zone yet. Build a zone core (free blueprint) and place it; within 32 blocks place an enemy portal and a single line of path blocks from the portal to the core. Towers go next to the path.");
            add("craftorio.td.next_level", "Next level");
            add("craftorio.td.wave", "Wave");
            add("craftorio.td.lives", "Lives");
            add("craftorio.td.enemies", "Enemies left");
            add("craftorio.td.reward", "Reward");
            add("craftorio.td.milestone", "Next key material");
            add("craftorio.td.milestone.in", "in %s levels");
            add("craftorio.td.key_next", "This level awards a key material!");
            add("craftorio.td.rules", "A level is lost when %s lives are gone. Enemies only attack towers – your factory is safe. Destroyed towers leave ruins you can rebuild.");
            add("craftorio.td.button.start", "Start level %s");
            add("craftorio.td.button.auto_on", "Auto-continue: on");
            add("craftorio.td.button.auto_off", "Auto-continue: off");
            add("craftorio.td.button.repair", "Repair all towers (%s)");
            add("craftorio.td.started", "Level %s started!");
            add("craftorio.td.won", "Level %s won! +%s");
            add("craftorio.td.lost", "Level %s lost – repair or upgrade your towers and try again.");
            add("craftorio.td.key_reward", "Key material %s dropped at the zone core!");
            add("craftorio.td.path_ok", "Path OK: %s blocks from portal to core.");
            add("craftorio.td.repair.nothing", "Nothing to repair.");
            add("craftorio.td.repair.too_expensive", "Not enough credits (%s needed).");
            add("craftorio.td.repair.done", "Towers repaired for %s.");
            add("craftorio.td.error.no_zone", "Your team has no defense zone.");
            add("craftorio.td.error.running", "A level is already running.");
            add("craftorio.td.error.no_portal", "The zone has no enemy portal.");
            add("craftorio.td.error.no_team", "You are not in a team.");
            add("craftorio.td.error.zone_exists", "Your team already has a zone core.");
            add("craftorio.td.error.overworld_only", "Defense zones only work in the overworld.");
            add("craftorio.td.error.outside_zone", "Only inside your defense zone (%s blocks around the zone core).");
            add("craftorio.td.error.foreign_zone", "This zone core belongs to another team.");
            add("craftorio.td.error.path.no_start", "No path block next to the enemy portal.");
            add("craftorio.td.error.path.branch", "The path branches – it must be a single line.");
            add("craftorio.td.error.path.dead_end", "The path ends before it reaches the zone core.");
            add("craftorio.td.error.path.too_short", "The path is too short (at least %s blocks).");
            add("craftorio.td.error.path.too_long", "The path is too long.");
            add("craftorio.tower.upgrade", "Upgrade");
            add("craftorio.tower.level", "Level %s");
            add("craftorio.tower.upgraded", "Tower upgraded to level %s for %s");
            add("craftorio.tower.rebuilt", "Tower rebuilt for %s");

            add(ModBlocks.CAVE_RUBBLE.get(), "Cave Rubble");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Cave Entrance");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Tin Ore Field");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Lead Ore Field");
            add(ModBlocks.SULFUR_FIELD.get(), "Sulfur Field");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Gold Ore Field");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quartz Field");
            add(ModItems.RAW_TIN.get(), "Raw Tin");
            add(ModItems.TIN_INGOT.get(), "Tin Ingot");
            add(ModItems.RAW_LEAD.get(), "Raw Lead");
            add(ModItems.LEAD_INGOT.get(), "Lead Ingot");
            add(ModItems.SULFUR.get(), "Sulfur");
            add(ModItems.BATTERY.get(), "Battery");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Advanced Circuit");
            add(ModBlocks.ELEVATOR.get(), "Item Elevator");
            add("craftorio.elevator.mode.receive", "Mode: receive (outputs through the front)");
            add("craftorio.elevator.mode.send_up", "Mode: send up");
            add("craftorio.elevator.mode.send_down", "Mode: send down");
            add("craftorio.elevator.target", "→ partner %s blocks away");
            add("craftorio.elevator.no_target", "→ no elevator in this column!");
            add("craftorio.cave.needs", "Construction site needs:");
            add("craftorio.cave.drilling", "Drilling: %s%% (needs %s FE/t from a power pole)");
            add("craftorio.cave.open", "Cave entrance open – take the scaffolding down (sneak to descend).");
            add("craftorio.cave.opened", "A cave entrance has opened! The cave area around chunk %s, %s is being dug out.");
            add("craftorio.cave.error.overworld_only", "Cave entrances only work in the overworld.");
            add("craftorio.cave.error.too_deep", "Build cave entrances on the surface (Y 50 or higher).");
            add("craftorio.cave.error.no_layer", "There is no cave layer below this spot (area generated before the cave update).");

            add("craftorio.drill.status", "Drill: %s/%s field blocks · %s items/s · fuel for %s s");
            add("craftorio.drill.overlap", "Too close to another drill – mining areas must not overlap.");
            add(ModBlocks.MINE_RUBBLE.get(), "Mine Rubble");
            add(ModBlocks.MINE_SHAFT.get(), "Mine Shaft");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamond Field");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanium Ore Field");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranium Ore Field");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Crystal Field");
            add(ModItems.RAW_TITANIUM.get(), "Raw Titanium");
            add(ModItems.TITANIUM_INGOT.get(), "Titanium Ingot");
            add(ModItems.TITANIUM_PLATE.get(), "Titanium Plate");
            add(ModItems.RAW_URANIUM.get(), "Raw Uranium");
            add(ModItems.URANIUM_PELLET.get(), "Uranium Pellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Crystal Shard");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energy Crystal");
            add(ModItems.FUEL_ROD.get(), "Fuel Rod");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Electric Drill");
            add(ModBlocks.DEEP_DRILL.get(), "Deep Drill");
            add(ModBlocks.FAST_BELT.get(), "Fast Belt");
            add(ModBlocks.EXPRESS_BELT.get(), "Express Belt");
            add(ModBlocks.REACTOR.get(), "Reactor");
            add(ModBlocks.LASER_TOWER.get(), "Laser Tower");
            add("entity.craftorio.crystal_golem", "Crystal Golem");
            add("craftorio.command.layer_unlocked", "Unlocked %s chunks of the layer (Y %s to %s); they are being dug out.");
            add("craftorio.mine.open", "Mine shaft open – take the scaffolding down into the mine layer.");
            add("craftorio.mine.opened", "A mine shaft has opened! The mine area around chunk %s, %s is being dug out.");
            add("craftorio.mine.error.not_in_caves", "Build mine shafts in an unlocked area of the cave layer (Y 0 to 39).");
            add("craftorio.drill.status_electric", "Drill: %s/%s field blocks · %s items/s · %s FE stored (needs %s FE/t)");

            add("craftorio.tooltip.sell_price", "Sell value: %s");
            add("craftorio.tooltip.sell_price_stack", "Sell value: %s (stack: %s)");
            add("craftorio.trading_post.sold", "Sold for %s");
            add("craftorio.trading_post.info", "Trading post of team %s – earned so far: %s");

            add("craftorio.command.credits", "Team %s has %s");
            add("craftorio.command.team.info", "Team %s – balance: %s – members: %s");
            add("craftorio.command.team.list_entry", "%s (%s members)");
            add("craftorio.command.team.created", "Team %s created.");
            add("craftorio.command.team.invited", "%s invited you to team %s.");
            add("craftorio.command.team.invite_sent", "Invitation sent to %s.");
            add("craftorio.command.team.joined", "You joined team %s.");
            add("craftorio.command.team.left", "You left your team and now play as team %s.");

            add("craftorio.team.error.name_taken", "A team named %s already exists.");
            add("craftorio.team.error.invalid_name", "Team names must be 1–%s characters: letters, digits, spaces, _ and -.");
            add("craftorio.team.error.no_team", "You are not in a team.");
            add("craftorio.team.error.already_member", "That player is already in this team.");
            add("craftorio.team.error.unknown_team", "There is no team named %s.");
            add("craftorio.team.error.not_invited", "You have not been invited to team %s.");
            add("craftorio.team.error.alone", "You are the only member of your team.");
            add("craftorio.command.team.rights", "Leader: %s – spending: %s");
            add("craftorio.command.team.spending.all", "all members");
            add("craftorio.command.team.spending.leader", "leader only");
            add("craftorio.command.team.spending.set_all", "All members may now spend the team's credits.");
            add("craftorio.command.team.spending.set_leader", "Only the leader may spend the team's credits now.");
            add("craftorio.command.team.kicked", "%s was removed from the team.");
            add("craftorio.command.team.kicked_you", "You were removed from team %s and now play in your own team.");
            add("craftorio.command.team.new_leader", "%s now leads the team.");
            add("craftorio.team.error.not_leader", "Only the team leader can do that.");
            add("craftorio.team.error.not_member", "That player is not in your team.");
            add("craftorio.team.error.kick_self", "You cannot kick yourself – use /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Only your team leader may spend credits.");
            add("craftorio.team.error.one_player", "Name exactly one player.");
            add("craftorio.protection.denied", "This belongs to team %s.");
            add("craftorio.quest.first_sale", "Sell anything at a trading post");
            add("craftorio.quest.sell_raw_iron", "Sell 64 raw iron");
            add("craftorio.quest.unlock_coal_generator", "Buy the coal generator blueprint");
            add("craftorio.quest.unlock_press", "Buy the press blueprint");
            add("craftorio.quest.sell_iron_plate", "Sell 100 iron plates");
            add("craftorio.quest.earn_10k", "Earn 10.000 ¢ in total");
            add("craftorio.quest.td_5", "Complete tower defense level 5");
            add("craftorio.quest.unlock_workbench_upgrade_2", "Upgrade to the assembly workbench");
            add("craftorio.quest.unlock_assembler", "Buy the assembler blueprint");
            add("craftorio.quest.sell_motor", "Sell 20 motors");
            add("craftorio.quest.unlock_cave_entrance", "Buy the cave entrance blueprint");
            add("craftorio.quest.sell_tin_ingot", "Sell 64 tin ingots from the caves");
            add("craftorio.quest.sell_battery", "Sell 32 batteries");
            add("craftorio.quest.td_20", "Complete tower defense level 20");
            add("craftorio.quest.unlock_mine_shaft", "Buy the mine shaft blueprint");
            add("craftorio.quest.sell_titanium_plate", "Sell 64 titanium plates");
            add("craftorio.quest.sell_energy_crystal", "Sell 8 energy crystals");
            add("craftorio.quest.earn_1m", "Earn 1.000.000 ¢ in total");
            add("craftorio.quest.td_40", "Complete tower defense level 40");
            add("craftorio.terminal.tab.quests", "Guide");
            add("craftorio.quest.claim", "Collect");
            add("craftorio.quest.done", "Done ✔");
            add("craftorio.quest.ready", "Reached!");
            add("craftorio.quest.open", "Not done yet");
            add("craftorio.quest.not_done", "This goal is not reached yet.");
            add("craftorio.quest.claimed", "Guide: %s – %s collected");
        }
    }

    public static final class German extends LanguageProvider {
        public German(PackOutput output) {
            super(output, Craftorio.MOD_ID, "de_de");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Deckgestein");
            add(ModBlocks.TRADING_POST.get(), "Handelsposten");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Eisenerzfeld");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Kupfererzfeld");
            add(ModBlocks.COAL_FIELD.get(), "Kohlefeld");
            add(ModBlocks.BURNER_DRILL.get(), "Brenner-Bohrer");
            add(ModBlocks.CONVEYOR_BELT.get(), "Förderband");
            add(ModBlocks.INSERTER.get(), "Greifarm");

            add(ModBlocks.COAL_GENERATOR.get(), "Kohle-Generator");
            add(ModBlocks.POWER_POLE.get(), "Strommast");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Elektro-Schmelzofen");
            add(ModBlocks.PRESS.get(), "Presse");
            add(ModBlocks.ASSEMBLER.get(), "Montagemaschine");
            add(ModItems.IRON_PLATE.get(), "Eisenplatte");
            add(ModItems.COPPER_CABLE.get(), "Kupferkabel");
            add(ModItems.IRON_GEAR.get(), "Zahnrad");
            add(ModItems.CIRCUIT.get(), "Schaltkreis");
            add(ModItems.MOTOR.get(), "Motor");

            add("craftorio.gui.energy", "Energie: %s / %s FE");
            add("craftorio.gui.no_recipe", "Rezept wählen");
            add("craftorio.power.no_network", "Nicht verbunden");
            add("craftorio.power.network", "Netz: %s Masten · %s Generatoren · %s Verbraucher · %s/%s FE/t · %s%% versorgt");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Konstruktionswerkbank");
            add(ModBlocks.ASSEMBLY_WORKBENCH.get(), "Montagewerkbank");
            add(ModBlocks.PRECISION_WORKBENCH.get(), "Präzisionswerkbank");
            add(ModItems.WORKBENCH_UPGRADE_2.get(), "Werkbank-Aufrüstsatz (Stufe 2)");
            add(ModItems.WORKBENCH_UPGRADE_3.get(), "Werkbank-Aufrüstsatz (Stufe 3)");
            add(ModItems.DRILL_CORE.get(), "Bohrkern");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonanzkristall");
            add(ModItems.DEEP_CORE.get(), "Tiefenkern");
            add(ModItems.STAR_SHARD.get(), "Sternenerz-Splitter");

            add("craftorio.key_material.hint", "Schlüsselmaterial – Belohnung für Tower-Defense-Level %s");
            add("craftorio.workbench.upgrade_hint", "Rechtsklick auf eine Werkbank der Stufe %s rüstet sie auf");
            add("craftorio.workbench.upgrade_target", "Funktioniert nur an einer Werkbank der Stufe %s");
            add("craftorio.workbench.hint", "Klick: 1 bauen · Shift-Klick: 10 bauen");
            add("craftorio.workbench.build", "Bauen");
            add("craftorio.workbench.locked", "Gesperrt");
            add("craftorio.workbench.needs_tier", "Braucht Werkbank Stufe %s");
            add("craftorio.workbench.tier_too_low", "Dieser Bauplan braucht eine Werkbank der Stufe %s");
            add("craftorio.workbench.missing", "Material fehlt");
            add("craftorio.terminal.tab.blueprints", "Baupläne");
            add("craftorio.terminal.tab.stats", "Statistik");
            add("craftorio.terminal.unlock", "Kaufen");
            add("craftorio.terminal.stats.earned", "Gesamt eingenommen");
            add("craftorio.terminal.stats.spent", "Gesamt ausgegeben");
            add("craftorio.terminal.stats.recent", "Eingenommen in den letzten 10 Minuten");
            add("craftorio.terminal.stats.top", "Meistverkauft");
            add("craftorio.blueprint.tier", "Stufe %s");
            add("craftorio.blueprint.requires", "braucht %s");
            add("craftorio.blueprint.materials", "Material:");
            add("craftorio.blueprint.unlock_items", "Freischalten braucht zusätzlich:");
            add("craftorio.blueprint.unlocked", "Bauplan %s für %s freigeschaltet");
            add("craftorio.blueprint.locked", "Dieser Bauplan ist noch nicht freigeschaltet");
            add("craftorio.blueprint.status.unlocked", "freigeschaltet");
            add("craftorio.blueprint.status.available", "verfügbar");
            add("craftorio.blueprint.status.missing_prerequisite", "Erst die Voraussetzung freischalten");
            add("craftorio.blueprint.status.missing_key_items", "braucht Schlüsselmaterial");
            add("craftorio.blueprint.status.not_enough_credits", "zu wenig Credits");

            add(ModBlocks.ZONE_CORE.get(), "Zonenkern");
            add(ModBlocks.ENEMY_PORTAL.get(), "Feindportal");
            add(ModBlocks.PATH_BLOCK.get(), "Pfadblock");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Armbrustturm");
            add(ModBlocks.GUN_TURRET.get(), "Geschützturm");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla-Turm");
            add(ModBlocks.TOWER_RUIN.get(), "Turmruine");
            add(ModItems.BOLT.get(), "Bolzen");
            add(ModItems.CARTRIDGE.get(), "Patrone");
            add("entity.craftorio.crawler", "Krabbler");
            add("entity.craftorio.breaker", "Brecher");
            add("entity.craftorio.spitter", "Spucker");
            add("entity.craftorio.brood_mother", "Brutmutter");

            add("craftorio.terminal.tab.defense", "Abwehr");
            add("craftorio.hud.td", "Level %s · Welle %s/%s · Leben %s/%s · %s Gegner");
            add("craftorio.td.help", "Noch keine Verteidigungszone. Baue einen Zonenkern (Gratis-Bauplan) und stelle ihn auf. Im Umkreis von 32 Blöcken kommen ein Feindportal und eine durchgehende Linie aus Pfadblöcken vom Portal bis zum Kern dazu. Die Türme stellst du neben den Pfad.");
            add("craftorio.td.next_level", "Nächstes Level");
            add("craftorio.td.wave", "Welle");
            add("craftorio.td.lives", "Leben");
            add("craftorio.td.enemies", "Verbleibende Gegner");
            add("craftorio.td.reward", "Belohnung");
            add("craftorio.td.milestone", "Nächstes Schlüsselmaterial");
            add("craftorio.td.milestone.in", "in %s Leveln");
            add("craftorio.td.key_next", "Dieses Level bringt ein Schlüsselmaterial!");
            add("craftorio.td.rules", "Ein Level ist verloren, wenn %s Leben weg sind. Gegner greifen nur Türme an – die Fabrik bleibt sicher. Zerstörte Türme hinterlassen Ruinen, die du wieder aufbauen kannst.");
            add("craftorio.td.button.start", "Level %s starten");
            add("craftorio.td.button.auto_on", "Automatisch weiter: an");
            add("craftorio.td.button.auto_off", "Automatisch weiter: aus");
            add("craftorio.td.button.repair", "Alle Türme reparieren (%s)");
            add("craftorio.td.started", "Level %s gestartet!");
            add("craftorio.td.won", "Level %s geschafft! +%s");
            add("craftorio.td.lost", "Level %s verloren – repariere oder verbessere deine Türme und versuche es erneut.");
            add("craftorio.td.key_reward", "Schlüsselmaterial %s liegt am Zonenkern!");
            add("craftorio.td.path_ok", "Pfad OK: %s Blöcke vom Portal bis zum Kern.");
            add("craftorio.td.repair.nothing", "Nichts zu reparieren.");
            add("craftorio.td.repair.too_expensive", "Zu wenig Credits (%s nötig).");
            add("craftorio.td.repair.done", "Türme für %s repariert.");
            add("craftorio.td.error.no_zone", "Dein Team hat keine Verteidigungszone.");
            add("craftorio.td.error.running", "Es läuft bereits ein Level.");
            add("craftorio.td.error.no_portal", "In der Zone steht kein Feindportal.");
            add("craftorio.td.error.no_team", "Du bist in keinem Team.");
            add("craftorio.td.error.zone_exists", "Dein Team hat bereits einen Zonenkern.");
            add("craftorio.td.error.overworld_only", "Verteidigungszonen gibt es nur in der Oberwelt.");
            add("craftorio.td.error.outside_zone", "Nur innerhalb deiner Verteidigungszone (%s Blöcke um den Zonenkern).");
            add("craftorio.td.error.foreign_zone", "Dieser Zonenkern gehört einem anderen Team.");
            add("craftorio.td.error.path.no_start", "Neben dem Feindportal liegt kein Pfadblock.");
            add("craftorio.td.error.path.branch", "Der Pfad verzweigt sich – er muss eine einzige Linie sein.");
            add("craftorio.td.error.path.dead_end", "Der Pfad endet, bevor er den Zonenkern erreicht.");
            add("craftorio.td.error.path.too_short", "Der Pfad ist zu kurz (mindestens %s Blöcke).");
            add("craftorio.td.error.path.too_long", "Der Pfad ist zu lang.");
            add("craftorio.tower.upgrade", "Aufrüsten");
            add("craftorio.tower.level", "Stufe %s");
            add("craftorio.tower.upgraded", "Turm auf Stufe %s aufgerüstet für %s");
            add("craftorio.tower.rebuilt", "Turm für %s wieder aufgebaut");

            add(ModBlocks.CAVE_RUBBLE.get(), "Höhlengeröll");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Höhleneingang");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Zinnerzfeld");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Bleierzfeld");
            add(ModBlocks.SULFUR_FIELD.get(), "Schwefelfeld");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Golderzfeld");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quarzfeld");
            add(ModItems.RAW_TIN.get(), "Rohzinn");
            add(ModItems.TIN_INGOT.get(), "Zinnbarren");
            add(ModItems.RAW_LEAD.get(), "Rohblei");
            add(ModItems.LEAD_INGOT.get(), "Bleibarren");
            add(ModItems.SULFUR.get(), "Schwefel");
            add(ModItems.BATTERY.get(), "Batterie");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Fortgeschrittener Schaltkreis");
            add(ModBlocks.ELEVATOR.get(), "Warenaufzug");
            add("craftorio.elevator.mode.receive", "Modus: empfangen (Ausgabe nach vorne)");
            add("craftorio.elevator.mode.send_up", "Modus: nach oben senden");
            add("craftorio.elevator.mode.send_down", "Modus: nach unten senden");
            add("craftorio.elevator.target", "→ Gegenstück %s Blöcke entfernt");
            add("craftorio.elevator.no_target", "→ kein Aufzug in dieser Spalte!");
            add("craftorio.cave.needs", "Baustelle braucht noch:");
            add("craftorio.cave.drilling", "Bohrung: %s%% (braucht %s FE/t über einen Strommast)");
            add("craftorio.cave.open", "Höhleneingang offen – über das Gerüst hinab (Schleichen zum Absteigen).");
            add("craftorio.cave.opened", "Ein Höhleneingang wurde geöffnet! Der Höhlenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.cave.error.overworld_only", "Höhleneingänge gibt es nur in der Oberwelt.");
            add("craftorio.cave.error.too_deep", "Höhleneingänge an der Oberfläche bauen (ab Y 50).");
            add("craftorio.cave.error.no_layer", "Unter dieser Stelle gibt es keine Höhlenschicht (Gebiet vor dem Höhlen-Update erzeugt).");

            add("craftorio.drill.status", "Bohrer: %s/%s Feldblöcke · %s Items/s · Brennstoff für %s s");
            add("craftorio.drill.overlap", "Zu nah an einem anderen Bohrer – Abbauflächen dürfen sich nicht überlappen.");
            add(ModBlocks.MINE_RUBBLE.get(), "Minengeröll");
            add(ModBlocks.MINE_SHAFT.get(), "Minenschacht");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamantfeld");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanerzfeld");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranerzfeld");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Kristallfeld");
            add(ModItems.RAW_TITANIUM.get(), "Roh-Titan");
            add(ModItems.TITANIUM_INGOT.get(), "Titanbarren");
            add(ModItems.TITANIUM_PLATE.get(), "Titanplatte");
            add(ModItems.RAW_URANIUM.get(), "Roh-Uran");
            add(ModItems.URANIUM_PELLET.get(), "Uranpellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Kristallsplitter");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energiekristall");
            add(ModItems.FUEL_ROD.get(), "Brennstab");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Elektrischer Bohrer");
            add(ModBlocks.DEEP_DRILL.get(), "Tiefenbohrer");
            add(ModBlocks.FAST_BELT.get(), "Schnelles Förderband");
            add(ModBlocks.EXPRESS_BELT.get(), "Express-Förderband");
            add(ModBlocks.REACTOR.get(), "Reaktor");
            add(ModBlocks.LASER_TOWER.get(), "Laserturm");
            add("entity.craftorio.crystal_golem", "Kristallgolem");
            add("craftorio.command.layer_unlocked", "%s Chunks der Schicht freigeschaltet (Y %s bis %s); sie werden ausgehöhlt.");
            add("craftorio.mine.open", "Minenschacht offen – über das Gerüst hinab in die Minenschicht.");
            add("craftorio.mine.opened", "Ein Minenschacht wurde geöffnet! Der Minenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.mine.error.not_in_caves", "Minenschächte in einem freigeschalteten Bereich der Höhlenschicht bauen (Y 0 bis 39).");
            add("craftorio.drill.status_electric", "Bohrer: %s/%s Feldblöcke · %s Items/s · %s FE gespeichert (braucht %s FE/t)");

            add("craftorio.tooltip.sell_price", "Verkaufswert: %s");
            add("craftorio.tooltip.sell_price_stack", "Verkaufswert: %s (Stapel: %s)");
            add("craftorio.trading_post.sold", "Verkauft für %s");
            add("craftorio.trading_post.info", "Handelsposten von Team %s – bisher eingenommen: %s");

            add("craftorio.command.credits", "Team %s hat %s");
            add("craftorio.command.team.info", "Team %s – Kontostand: %s – Mitglieder: %s");
            add("craftorio.command.team.list_entry", "%s (%s Mitglieder)");
            add("craftorio.command.team.created", "Team %s gegründet.");
            add("craftorio.command.team.invited", "%s hat dich in Team %s eingeladen.");
            add("craftorio.command.team.invite_sent", "Einladung an %s gesendet.");
            add("craftorio.command.team.joined", "Du bist Team %s beigetreten.");
            add("craftorio.command.team.left", "Du hast dein Team verlassen und spielst jetzt als Team %s.");

            add("craftorio.team.error.name_taken", "Ein Team namens %s existiert bereits.");
            add("craftorio.team.error.invalid_name", "Teamnamen müssen 1–%s Zeichen lang sein: Buchstaben, Ziffern, Leerzeichen, _ und -.");
            add("craftorio.team.error.no_team", "Du bist in keinem Team.");
            add("craftorio.team.error.already_member", "Dieser Spieler ist bereits in diesem Team.");
            add("craftorio.team.error.unknown_team", "Es gibt kein Team namens %s.");
            add("craftorio.team.error.not_invited", "Du wurdest nicht in Team %s eingeladen.");
            add("craftorio.team.error.alone", "Du bist das einzige Mitglied deines Teams.");
            add("craftorio.command.team.rights", "Leitung: %s – Ausgaben: %s");
            add("craftorio.command.team.spending.all", "alle Mitglieder");
            add("craftorio.command.team.spending.leader", "nur Leitung");
            add("craftorio.command.team.spending.set_all", "Alle Mitglieder dürfen jetzt Credits des Teams ausgeben.");
            add("craftorio.command.team.spending.set_leader", "Nur noch die Teamleitung darf Credits ausgeben.");
            add("craftorio.command.team.kicked", "%s wurde aus dem Team entfernt.");
            add("craftorio.command.team.kicked_you", "Du wurdest aus Team %s entfernt und spielst jetzt in deinem eigenen Team.");
            add("craftorio.command.team.new_leader", "%s leitet jetzt das Team.");
            add("craftorio.team.error.not_leader", "Das darf nur die Teamleitung.");
            add("craftorio.team.error.not_member", "Dieser Spieler ist nicht in deinem Team.");
            add("craftorio.team.error.kick_self", "Du kannst dich nicht selbst entfernen – nutze /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Nur deine Teamleitung darf Credits ausgeben.");
            add("craftorio.team.error.one_player", "Gib genau einen Spieler an.");
            add("craftorio.protection.denied", "Das gehört Team %s.");
            add("craftorio.quest.first_sale", "Verkaufe etwas am Handelsposten");
            add("craftorio.quest.sell_raw_iron", "Verkaufe 64 Roheisen");
            add("craftorio.quest.unlock_coal_generator", "Kaufe den Bauplan Kohlegenerator");
            add("craftorio.quest.unlock_press", "Kaufe den Bauplan Presse");
            add("craftorio.quest.sell_iron_plate", "Verkaufe 100 Eisenplatten");
            add("craftorio.quest.earn_10k", "Verdiene insgesamt 10.000 ¢");
            add("craftorio.quest.td_5", "Schaffe Tower-Defense-Level 5");
            add("craftorio.quest.unlock_workbench_upgrade_2", "Rüste auf die Montagewerkbank auf");
            add("craftorio.quest.unlock_assembler", "Kaufe den Bauplan Montagemaschine");
            add("craftorio.quest.sell_motor", "Verkaufe 20 Motoren");
            add("craftorio.quest.unlock_cave_entrance", "Kaufe den Bauplan Höhleneingang");
            add("craftorio.quest.sell_tin_ingot", "Verkaufe 64 Zinnbarren aus den Höhlen");
            add("craftorio.quest.sell_battery", "Verkaufe 32 Batterien");
            add("craftorio.quest.td_20", "Schaffe Tower-Defense-Level 20");
            add("craftorio.quest.unlock_mine_shaft", "Kaufe den Bauplan Minenschacht");
            add("craftorio.quest.sell_titanium_plate", "Verkaufe 64 Titanplatten");
            add("craftorio.quest.sell_energy_crystal", "Verkaufe 8 Energiekristalle");
            add("craftorio.quest.earn_1m", "Verdiene insgesamt 1.000.000 ¢");
            add("craftorio.quest.td_40", "Schaffe Tower-Defense-Level 40");
            add("craftorio.terminal.tab.quests", "Leitfaden");
            add("craftorio.quest.claim", "Abholen");
            add("craftorio.quest.done", "Erledigt ✔");
            add("craftorio.quest.ready", "Erreicht!");
            add("craftorio.quest.open", "Noch offen");
            add("craftorio.quest.not_done", "Dieses Ziel ist noch nicht erreicht.");
            add("craftorio.quest.claimed", "Leitfaden: %s – %s erhalten");
        }
    }
}
