package de.craftorio.datagen;

import net.minecraft.world.item.Items;
import de.craftorio.Craftorio;
import de.craftorio.registry.ModBlocks;
import de.craftorio.registry.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public final class ModLanguageProvider {
    private ModLanguageProvider() {
    }

    public static final class English extends LanguageProvider {
        public English(PackOutput output) {
            super(output, Craftorio.MOD_ID, "en_us");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Cap Rock");
            add(ModBlocks.TRADING_POST.get(), "Trading Post");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Iron Ore Field");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Copper Ore Field");
            add(ModBlocks.COAL_FIELD.get(), "Coal Field");
            add(ModBlocks.BURNER_DRILL.get(), "Burner Drill");
            add(ModBlocks.CONVEYOR_BELT.get(), "Conveyor Belt");
            add(ModBlocks.INSERTER.get(), "Inserter");

            add(ModBlocks.BOILER.get(), "Boiler");
            add(ModBlocks.STEAM_ENGINE.get(), "Steam Engine");
            add(ModBlocks.OFFSHORE_PUMP.get(), "Offshore Pump");
            add(ModBlocks.STONE_FIELD.get(), "Stone Field");
            add(ModBlocks.WOOD_FIELD.get(), "Wood Field");
            add(ModItems.PIPE.get(), "Pipe");
            add(ModItems.STONE_BRICK.get(), "Stone Brick");
            add(ModBlocks.POWER_POLE.get(), "Power Pole");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Electric Furnace");
            add(ModBlocks.STONE_FURNACE.get(), "Stone Furnace");
            add(ModBlocks.ASSEMBLER.get(), "Assembling Machine 1");
            add(ModItems.COPPER_CABLE.get(), "Copper Cable");
            add(ModItems.IRON_GEAR.get(), "Iron Gear");
            add(ModItems.CIRCUIT.get(), "Circuit");
            add(ModItems.MOTOR.get(), "Motor");
            add(ModItems.STEEL_PLATE.get(), "Steel Plate");
            add(ModItems.IRON_STICK.get(), "Iron Rod");
            add(ModBlocks.MEDIUM_POWER_POLE.get(), "Medium Power Pole");
            add(ModBlocks.SOLAR_PANEL.get(), "Solar Panel");
            add(ModBlocks.STEEL_FURNACE.get(), "Steel Furnace");
            add(ModBlocks.ASSEMBLER_2.get(), "Assembling Machine 2");
            add("craftorio.solar.output", "Solar panel: %s of %s kW");
            add("craftorio.solar.no_sky", "The solar panel needs open sky");
            add("craftorio.research.electronics", "Electronics");
            add("craftorio.research.steel_processing", "Steel Processing");
            add("craftorio.research.logistic_science_pack", "Logistic Science Pack");
            add("craftorio.research.automation_2", "Automation 2");
            add("craftorio.research.electric_energy_distribution_1", "Electric Energy Distribution 1");
            add("craftorio.research.advanced_material_processing", "Advanced Material Processing");
            add("craftorio.research.solar_energy", "Solar Energy");

            add("craftorio.gui.energy", "Energy: %s / %s FE");
            add("craftorio.gui.no_recipe", "Choose a recipe");
            add("craftorio.power.no_network", "Not connected");
            add("craftorio.power.network", "Grid: %s poles · %s generators · %s consumers · %s/%s FE/t · %s%% supplied");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Construction Workbench");
            add(ModItems.DRILL_CORE.get(), "Drill Core");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonance Crystal");
            add(ModItems.DEEP_CORE.get(), "Deep Core");
            add(ModItems.STAR_SHARD.get(), "Star Shard");

            add("craftorio.key_material.hint", "Key material – reward for tower defense level %s");
            add("craftorio.workbench.hint", "Click: build 1 · Shift-click: build 10");
            add("craftorio.workbench.build", "Build");
            add("craftorio.workbench.can_build", "ready to build");
            add("craftorio.research.electric_smelting", "Electric Smelting");
            add("craftorio.boiler.water", "Water: pump connected");
            add("craftorio.boiler.no_water", "No water: put an offshore pump at the shore next to the boiler");
            add("craftorio.steam_engine.status.0", "Running: 900 kW");
            add("craftorio.steam_engine.status.1", "No boiler next to the engine");
            add("craftorio.steam_engine.status.3", "Ready, but nobody takes the power: connect a power pole and a consumer");
            add("craftorio.steam_engine.status.2", "The boiler has no steam (fuel or water missing, or two engines already use it)");
            add("craftorio.workbench.locked", "Needs research");
            add("craftorio.workbench.missing", "Missing materials");
            add("craftorio.terminal.tab.stats", "Statistics");
            add("craftorio.research.automation", "Automation");
            add("craftorio.research.turrets", "Turrets");
            add("craftorio.research.gun_turrets", "Gun Turrets");
            add("craftorio.research.energy_turrets", "Energy Turrets");
            add("craftorio.research.engines", "Engine");
            add("craftorio.research.caves", "Cave Access");
            add("craftorio.research.elevators", "Cargo Elevators");
            add("craftorio.research.fast_belts", "Fast Belts");
            add("craftorio.research.mine_shaft", "Mine Shaft");
            add("craftorio.research.deep_mining", "Deep Mining");
            add("craftorio.research.express_belts", "Express Belts");
            add("craftorio.research.nuclear_power", "Nuclear Power");
            add("craftorio.research.laser_turrets", "Laser Turrets");
            add("craftorio.terminal.tab.research", "Research");
            add("craftorio.research.queue", "Research");
            add("craftorio.terminal.stats.research", "Finished researches (world time)");
            add("craftorio.research.remove", "Remove");
            add("craftorio.research.status.done", "researched");
            add("craftorio.research.status.active", "in progress: %s / %s units");
            add("craftorio.research.status.queued", "queued (position %s)");
            add("craftorio.research.status.locked", "needs %s");
            add("craftorio.research.cost", "Cost: %s");
            add("craftorio.research.requires", "Requires:");
            add("craftorio.research.unlocks", "Unlocks:");
            add("craftorio.research.key_items", "Handed in once when started:");
            add("craftorio.research.locked", "Finish or queue the prerequisites first");
            add("craftorio.research.missing_key_items", "You need the key material in your inventory");
            add("craftorio.research.finished", "Research finished: %s");
            add("craftorio.lab.status.0", "Idle");
            add("craftorio.lab.status.1", "Not owned by a team");
            add("craftorio.lab.status.2", "No research selected");
            add("craftorio.lab.status.3", "Science packs missing");
            add("craftorio.lab.status.4", "Researching");
            add("craftorio.lab.status.5", "No power");
            add("craftorio.guide.research_then_build", "Research %s in the terminal, then build it at the %s from:");
            add("craftorio.emi.research", "Research: %s");
            add(ModBlocks.LABORATORY.get(), "Laboratory");
            add(ModItems.RED_SCIENCE.get(), "Automation Science Pack");
            add(ModItems.GREEN_SCIENCE.get(), "Logistic Science Pack");
            add(ModItems.MILITARY_SCIENCE.get(), "Military Science Pack");
            add(ModItems.BLUE_SCIENCE.get(), "Chemical Science Pack");
            add("craftorio.terminal.stats.earned", "Total earned");
            add("craftorio.terminal.stats.spent", "Total spent");
            add("craftorio.terminal.stats.recent", "Earned in the last 10 minutes");
            add("craftorio.terminal.stats.top", "Best sellers");
            add("craftorio.blueprint.materials", "Materials:");
            add("craftorio.blueprint.locked", "This recipe needs a research first");

            add(ModBlocks.ZONE_CORE.get(), "Zone Core");
            add(ModBlocks.ENEMY_PORTAL.get(), "Enemy Portal");
            add(ModBlocks.PATH_BLOCK.get(), "Path Block");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Crossbow Tower");
            add(ModBlocks.GUN_TURRET.get(), "Gun Turret");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla Tower");
            add(ModBlocks.TOWER_RUIN.get(), "Tower Ruin");
            add(ModItems.BOLT.get(), "Bolt");
            add(ModItems.CARTRIDGE.get(), "Cartridge");
            add("entity.craftorio.crawler", "Crawler");
            add("entity.craftorio.breaker", "Breaker");
            add("entity.craftorio.spitter", "Spitter");
            add("entity.craftorio.brood_mother", "Brood Mother");

            add("craftorio.terminal.tab.defense", "Defense");
            add("craftorio.hud.td", "Level %s · wave %s/%s · lives %s/%s · %s enemies");
            add("craftorio.td.next_level", "Next level");
            add("craftorio.td.wave", "Wave");
            add("craftorio.td.lives", "Lives");
            add("craftorio.td.enemies", "Enemies left");
            add("craftorio.td.reward", "Reward");
            add("craftorio.td.milestone", "Next key material");
            add("craftorio.td.milestone.in", "in %s levels");
            add("craftorio.td.key_next", "This level awards a key material!");
            add("craftorio.td.rules", "A level is lost when %s lives are gone. Enemies only attack towers – your factory is safe. Destroyed towers leave ruins you can rebuild.");
            add("craftorio.td.button.start", "Start level %s");
            add("craftorio.td.button.auto_on", "Auto-continue: on");
            add("craftorio.td.button.auto_off", "Auto-continue: off");
            add("craftorio.td.button.repair", "Repair all towers (%s)");
            add("craftorio.td.started", "Level %s started!");
            add("craftorio.td.won", "Level %s won! +%s");
            add("craftorio.td.lost", "Level %s lost – repair or upgrade your towers and try again.");
            add("craftorio.td.repair.nothing", "Nothing to repair.");
            add("craftorio.td.repair.too_expensive", "Not enough credits (%s needed).");
            add("craftorio.td.repair.done", "Towers repaired for %s.");
            add("craftorio.td.error.no_zone", "Your team has no defense zone.");
            add("craftorio.td.error.running", "A level is already running.");
            add("craftorio.td.error.no_portal", "The zone has no enemy portal.");
            add("craftorio.td.error.no_team", "You are not in a team.");
            add("craftorio.td.error.zone_exists", "Your team already has a zone core.");
            add("craftorio.td.error.overworld_only", "Defense zones only work in the overworld.");
            add("craftorio.td.error.outside_zone", "Only inside your defense zone (%s blocks around the zone core).");
            add("craftorio.td.error.foreign_zone", "This zone core belongs to another team.");
            add("craftorio.td.error.path.no_start", "No path block next to the enemy portal.");
            add("craftorio.td.error.path.branch", "The path branches – it must be a single line.");
            add("craftorio.td.error.path.dead_end", "The path ends before it reaches the zone core.");
            add("craftorio.td.error.path.too_short", "The path is too short (at least %s blocks).");
            add("craftorio.td.error.path.too_long", "The path is too long.");
            add("craftorio.tower.upgrade", "Upgrade");
            add("craftorio.tower.level", "Level %s");
            add("craftorio.tower.upgraded", "Tower upgraded to level %s for %s");
            add("craftorio.tower.rebuilt", "Tower rebuilt for %s");

            add(ModBlocks.CAVE_RUBBLE.get(), "Cave Rubble");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Cave Entrance");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Tin Ore Field");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Lead Ore Field");
            add(ModBlocks.SULFUR_FIELD.get(), "Sulfur Field");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Gold Ore Field");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quartz Field");
            add(ModItems.RAW_TIN.get(), "Raw Tin");
            add(ModItems.TIN_INGOT.get(), "Tin Ingot");
            add(ModItems.RAW_LEAD.get(), "Raw Lead");
            add(ModItems.LEAD_INGOT.get(), "Lead Ingot");
            add(ModItems.SULFUR.get(), "Sulfur");
            add(ModItems.BATTERY.get(), "Battery");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Advanced Circuit");
            add(ModBlocks.ELEVATOR.get(), "Item Elevator");
            add("craftorio.elevator.mode.receive", "Mode: receive (outputs through the front)");
            add("craftorio.elevator.mode.send_up", "Mode: send up");
            add("craftorio.elevator.mode.send_down", "Mode: send down");
            add("craftorio.elevator.target", "→ partner %s blocks away");
            add("craftorio.elevator.no_target", "→ no elevator in this column!");
            add("craftorio.cave.needs", "Construction site needs:");
            add("craftorio.cave.drilling", "Drilling: %s%% (needs %s FE/t from a power pole)");
            add("craftorio.cave.open", "Cave entrance open – take the scaffolding down (sneak to descend).");
            add("craftorio.cave.opened", "A cave entrance has opened! The cave area around chunk %s, %s is being dug out.");
            add("craftorio.cave.error.overworld_only", "Cave entrances only work in the overworld.");
            add("craftorio.cave.error.too_deep", "Build cave entrances on the surface (Y 50 or higher).");
            add("craftorio.cave.error.no_layer", "There is no cave layer below this spot (area generated before the cave update).");

            add("craftorio.drill.status", "Drill: %s/%s field blocks · %s items/s · fuel for %s s");
            add("craftorio.drill.gui_fields", "Field blocks: %s/%s");
            add("craftorio.drill.gui_rate", "%s items/s");
            add("craftorio.drill.gui_no_field", "Place it on an ore field!");
            add("craftorio.drill.overlap", "Too close to another drill – mining areas must not overlap.");
            add(ModBlocks.MINE_RUBBLE.get(), "Mine Rubble");
            add(ModBlocks.MINE_SHAFT.get(), "Mine Shaft");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamond Field");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanium Ore Field");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranium Ore Field");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Crystal Field");
            add(ModItems.RAW_TITANIUM.get(), "Raw Titanium");
            add(ModItems.TITANIUM_INGOT.get(), "Titanium Ingot");
            add(ModItems.TITANIUM_PLATE.get(), "Titanium Plate");
            add(ModItems.RAW_URANIUM.get(), "Raw Uranium");
            add(ModItems.URANIUM_PELLET.get(), "Uranium Pellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Crystal Shard");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energy Crystal");
            add(ModItems.FUEL_ROD.get(), "Fuel Rod");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Electric Drill");
            add(ModBlocks.DEEP_DRILL.get(), "Deep Drill");
            add(ModBlocks.FAST_BELT.get(), "Fast Belt");
            add(ModBlocks.EXPRESS_BELT.get(), "Express Belt");
            add(ModBlocks.REACTOR.get(), "Reactor");
            add(ModBlocks.LASER_TOWER.get(), "Laser Tower");
            add("entity.craftorio.crystal_golem", "Crystal Golem");
            add("craftorio.command.layer_unlocked", "Unlocked %s chunks of the layer (Y %s to %s); they are being dug out.");
            add("craftorio.mine.open", "Mine shaft open – take the scaffolding down into the mine layer.");
            add("craftorio.mine.opened", "A mine shaft has opened! The mine area around chunk %s, %s is being dug out.");
            add("craftorio.mine.error.not_in_caves", "Build mine shafts in an unlocked area of the cave layer (Y 0 to 39).");
            add("craftorio.drill.status_electric", "Drill: %s/%s field blocks · %s items/s · %s FE stored (needs %s FE/t)");

            add("craftorio.tooltip.sell_price", "Sell value: %s");
            add("craftorio.tooltip.sell_price_stack", "Sell value: %s (stack: %s)");
            add("craftorio.trading_post.sold", "Sold for %s");
            add("craftorio.trading_post.info", "Trading post of team %s – earned so far: %s");
            add("craftorio.trading_post.value", "Value: %s");
            add("craftorio.trading_post.sell", "Sell");
            add("craftorio.trading_post.owner", "Team: %s");
            add("craftorio.trading_post.earned", "Total: %s");

            add("craftorio.command.credits", "Team %s has %s");
            add("craftorio.command.team.info", "Team %s – balance: %s – members: %s");
            add("craftorio.command.team.list_entry", "%s (%s members)");
            add("craftorio.command.team.created", "Team %s created.");
            add("craftorio.command.team.invited", "%s invited you to team %s.");
            add("craftorio.command.team.invite_sent", "Invitation sent to %s.");
            add("craftorio.command.team.joined", "You joined team %s.");
            add("craftorio.command.team.left", "You left your team and now play as team %s.");

            add("craftorio.team.error.name_taken", "A team named %s already exists.");
            add("craftorio.team.error.invalid_name", "Team names must be 1–%s characters: letters, digits, spaces, _ and -.");
            add("craftorio.team.error.no_team", "You are not in a team.");
            add("craftorio.team.error.already_member", "That player is already in this team.");
            add("craftorio.team.error.unknown_team", "There is no team named %s.");
            add("craftorio.team.error.not_invited", "You have not been invited to team %s.");
            add("craftorio.team.error.alone", "You are the only member of your team.");
            add("craftorio.command.team.rights", "Leader: %s – spending: %s");
            add("craftorio.command.team.spending.all", "all members");
            add("craftorio.command.team.spending.leader", "leader only");
            add("craftorio.command.team.spending.set_all", "All members may now spend the team's credits.");
            add("craftorio.command.team.spending.set_leader", "Only the leader may spend the team's credits now.");
            add("craftorio.command.team.kicked", "%s was removed from the team.");
            add("craftorio.command.team.kicked_you", "You were removed from team %s and now play in your own team.");
            add("craftorio.command.team.new_leader", "%s now leads the team.");
            add("craftorio.team.error.not_leader", "Only the team leader can do that.");
            add("craftorio.team.error.not_member", "That player is not in your team.");
            add("craftorio.team.error.kick_self", "You cannot kick yourself – use /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Only your team leader may spend credits.");
            add("craftorio.team.error.one_player", "Name exactly one player.");
            add("craftorio.protection.denied", "This belongs to team %s.");
            add("craftorio.protection.too_close", "Too close to team %s – keep one block of space to their machines and containers.");
            add("emi.category.craftorio.pressing", "Pressing");
            add("emi.category.craftorio.assembling", "Assembling");
            add("emi.category.craftorio.blueprint", "Blueprint (workbench)");
            add("craftorio.emi.time", "%s s");
            add("craftorio.emi.free", "free");
            add("config.jade.plugin_craftorio.status", "Craftorio status");
            add("config.jade.plugin_craftorio.ore_field", "Craftorio ore fields");
            add("craftorio.jade.owner", "Owner: team %s");
            add("craftorio.jade.progress", "Progress: %s%%");
            add("craftorio.jade.tower", "HP %s / %s · level %s");
            add("craftorio.jade.ammo", "Ammunition: %s");
            add("craftorio.jade.ruin", "Destroyed – rebuild for %s");
            add("craftorio.jade.ore_field", "Yields %s (%s each) – endless");
            add("craftorio.terminal.tab.quests", "Guide");
            add("craftorio.workbench.missing_button", "Missing?");
            add("craftorio.workbench.missing_list", "Missing for %s:");
            add("craftorio.workbench.have", " (you have %s)");
            add("craftorio.toast.goal", "Reached! Press G");
            add("craftorio.starter_kit", "Welcome to Craftorio! Your starter kit: the handbook (press G), a starter pickaxe for ore fields and stone, a construction workbench and coal. Start by mining iron by hand – the handbook shows every step.");
            add(ModItems.GUIDE_BOOK.get(), "Craftorio Handbook");
            add(ModItems.STARTER_PICKAXE.get(), "Starter Pickaxe");
            add("key.craftorio.guide", "Open handbook");
            add("key.categories.craftorio", "Craftorio");
            add("craftorio.guide.current", "Current");
            add("craftorio.guide.claim", "Collect reward");
            add("craftorio.guide.step", "Guide · step %s of %s");
            add("craftorio.guide.progress", "Progress: %s");
            add("craftorio.guide.reward", "Reward: %s");
            add("craftorio.guide.build_at", "Build at the %s from:");
            add("craftorio.guide.crafting", "Recipe for the %s:");
            add("craftorio.guide.vanilla_table", "(normal crafting table)");
            add("craftorio.guide.value", "Sells for %s each");
            add("craftorio.guide.mined_from", "Mined from the %s – drill or by hand");
            add("craftorio.guide.made_in", "Made in the %s from:");
            add("craftorio.guide.smelted", "Smelted in a furnace or electric furnace:");
            add("craftorio.guide.earn", "Sell processed goods: the more processing steps, the higher the price. The terminal's statistics show what pays best.");
            add("craftorio.guide.defense", "Tower defense: go through your arena gate, lay a path with the path wand from the open gate to the core, place towers next to it and start the level in the terminal (Defense tab).");
            add("craftorio.hud.guide_key", "[%s] handbook");
            add("craftorio.hud.supply", "Arena supply: %s FE · %s bolts · %s cartridges");
            add("craftorio.hud.unsupplied", "%s tower(s) without supply! Build an arena feeder in your factory.");
            add("craftorio.tooltip.tower.energy", "Runs on power: supplied through the arena feeder in your factory.");
            add("craftorio.tooltip.tower.ammo", "Load it by hand or supply ammunition through the arena feeder in your factory.");
            add("craftorio.tooltip.arena_feeder", "Built in your factory: feeds power and ammunition into the arena, where the towers draw from it.");
            add("craftorio.arena.error.overworld_only", "Arena gates only work in the overworld.");
            add("craftorio.arena.error.not_arena", "Only in your arena.");
            add("craftorio.arena.error.outside_field", "Only inside the arena field.");
            add("craftorio.arena.error.foreign", "This is another team's arena.");
            add("craftorio.arena.error.no_tower_here", "Towers only stand on open ground or on a plateau – not on the path, trees, rock, water or lava.");
            add("craftorio.arena.error.no_building", "The arena cannot be changed – lay the path with the path wand and place towers.");
            add("craftorio.arena.path.blocked", "The path cannot go there.");
            add("craftorio.arena.path.route_hint", "The green particles show the shortest way from the gate to the core.");
            add("craftorio.arena.path.branch", "The path must stay a single line: no branches, junctions or 2x2 areas.");
            add("craftorio.arena.path_wand.tooltip", "Click the arena floor to lay path; the next click in the same row or column draws a straight line. Sneak-click removes path or starts a new line; sneak-click into the air shows the shortest way.");
            add("craftorio.arena.welcome", "Arena · level %s · map: %s – %s");
            add("craftorio.arena.new_map", "The arena has changed: new map %s. Your towers are waiting in the tower depot – lay a new path!");
            add("craftorio.arena.old_core", "Defense zones are now arenas – build an arena gate (free blueprint) and step through.");
            add("craftorio.arena.theme.forest", "Forest");
            add("craftorio.arena.theme.forest.rule", "Enemies in the thicket are camouflaged: towers spot them only at half range.");
            add("craftorio.arena.theme.mountain", "Mountains");
            add("craftorio.arena.theme.mountain.rule", "Towers on plateaus reach 30 % further; scree slows enemies.");
            add("craftorio.arena.theme.fire", "Fire");
            add("craftorio.arena.theme.fire.rule", "Lava vents erupt every few seconds and burn enemies walking over them.");
            add("craftorio.arena.theme.water", "Water");
            add("craftorio.arena.theme.water.rule", "The river can only be crossed at fords; shallow water slows enemies a lot.");
            add("craftorio.arena.theme.colosseum", "Colosseum");
            add("craftorio.arena.theme.colosseum.rule", "Boss level: open sand between pillars.");
            add("craftorio.arena.mutator.fog", "Mutator Fog: towers see 25 % less far (+25 % reward).");
            add("craftorio.arena.mutator.haste", "Mutator Forced march: enemies are 30 % faster (+25 % reward).");
            add("craftorio.arena.mutator.hardened", "Mutator Hardened: enemies have 35 % more health (+30 % reward).");
            add("craftorio.arena.depot.empty", "The tower depot is empty.");
            add("craftorio.arena.depot.take_all", "Take all");
            add("craftorio.arena.depot.taken", "Took %s stacks from the tower depot.");
            add("craftorio.arena.feeder.status", "Arena reserve: %s / %s FE · %s bolts · %s cartridges");
            add("craftorio.arena.feeder.no_owner", "This feeder belongs to no team.");
            add("craftorio.arena.feeder.no_arena", "Your team has no arena yet – go through an arena gate first.");
            add("craftorio.td.error.not_running", "No level is running.");
            add("craftorio.td.call.not_now", "The next wave can only be called between waves.");
            add("craftorio.td.call.done", "Next wave called early! +%s");
            add("craftorio.td.won_stars", "Level %s won %s! +%s");
            add("craftorio.td.button.call", "Call wave");
            add("craftorio.td.map", "Map");
            add("craftorio.td.last_stars", "Last level");
            add("craftorio.td.preview", "Next wave:");
            add("craftorio.td.reserves", "Arena reserve: %s FE · %s bolts · %s cartridges");
            add("craftorio.tower.target.first", "Target: first");
            add("craftorio.tower.target.last", "Target: last");
            add("craftorio.tower.target.strongest", "Target: strongest");
            add("craftorio.tower.target.weakest", "Target: weakest");
            add("craftorio.td.help", "No arena yet. Build an arena gate (free blueprint), place it in the overworld and right-click it. In your arena lay a path with the path wand from the open enemy gate to the core, then place towers on open ground. Every won level brings a new map.");
            add("craftorio.td.key_reward", "Key material %s is waiting in the tower depot!");
            add("craftorio.td.path_ok", "Path OK: %s blocks from the gate to the core.");
            add(ModBlocks.ARENA_BASE.get(), "Arena Floor");
            add(ModBlocks.ARENA_CLIFF.get(), "Plateau Rock");
            add(ModBlocks.ARENA_GATE.get(), "Arena Gate");
            add(ModBlocks.ARENA_EXIT.get(), "Arena Exit");
            add(ModBlocks.TOWER_DEPOT.get(), "Tower Depot");
            add(ModBlocks.ARENA_CONSOLE.get(), "Arena Console");
            add(ModBlocks.ARENA_FEEDER.get(), "Arena Feeder");
            add(ModItems.PATH_WAND.get(), "Path Wand");
            add("craftorio.quest.earn_10k", "Earn 10.000 ¢ in total");
            add("craftorio.quest.earn_10k.hint", "Expand: more drills, more fields, more processing. The Statistics tab shows what earns the most.");
            add("craftorio.quest.td_1", "Complete tower defense level 1");
            add("craftorio.quest.td_1.hint", "Start the level in the terminal's Defense tab. Enemies only attack towers – your factory is never in danger. Every won level brings a new map: take your towers from the tower depot.");
            add("craftorio.quest.td_10", "Complete tower defense level 10");
            add("craftorio.quest.td_10.hint", "Level 10 rewards the drill core – the key to the tier 2 workbench. Upgrade and repair your towers between levels.");
            add("craftorio.quest.sell_tin_ingot", "Sell 64 tin ingots");
            add("craftorio.quest.sell_tin_ingot.hint", "Tin, lead, sulfur, gold and quartz fields lie on the cave floor. Bring power down and set up drills there.");
            add("craftorio.quest.sell_battery", "Sell 32 batteries");
            add("craftorio.quest.sell_battery.hint", "Batteries are assembled from lead, sulfur and cables – a cave product worth far more than its parts.");
            add("craftorio.quest.td_20", "Complete tower defense level 20");
            add("craftorio.quest.td_20.hint", "From level 20 crystal golems come – only energy towers (tesla, laser) hurt them fully.");
            add("craftorio.quest.td_30", "Complete tower defense level 30");
            add("craftorio.quest.td_30.hint", "Level 30 rewards the deep core – the key to the precision workbench (tier 3).");
            add("craftorio.quest.sell_titanium_plate", "Sell 64 titanium plates");
            add("craftorio.quest.sell_titanium_plate.hint", "Smelt raw titanium, press the ingots. Deep drills (5×5) make the most of the mine fields.");
            add("craftorio.quest.sell_energy_crystal", "Sell 8 energy crystals");
            add("craftorio.quest.sell_energy_crystal.hint", "Energy crystals combine crystal shards, an advanced circuit and a battery – the most valuable good so far.");
            add("craftorio.quest.earn_1m", "Earn 1.000.000 ¢ in total");
            add("craftorio.quest.earn_1m.hint", "Scale up all three layers. Reactors burning fuel rods power the biggest factories.");
            add("craftorio.quest.td_40", "Complete tower defense level 40");
            add("craftorio.quest.td_40.hint", "The final challenge so far: laser towers and upgraded tesla towers against armoured waves.");
            add("craftorio.quest.mine_raw_iron", "Mine 16 raw iron");
            add("craftorio.quest.mine_raw_iron.hint", "Mine the iron ore field near the spawn by hand with the starter pickaxe.");
            add("craftorio.quest.mine_cobblestone", "Mine 20 stone");
            add("craftorio.quest.mine_cobblestone.hint", "Stone fields are big ore fields of cobblestone; you need stone for furnaces and, later, for bricks.");
            add("craftorio.quest.build_stone_furnace", "Build a stone furnace");
            add("craftorio.quest.build_stone_furnace.hint", "Open the construction workbench (in your starter kit) and build the stone furnace from 5 stone. Put coal into its fuel slot and raw ore into the input: it smelts to plates (ingots). It also makes stone bricks: put in at least 2 stone (2 stone → 1 brick, 3.2 s).");
            add("craftorio.quest.build_burner_drill", "Build a burner drill");
            add("craftorio.quest.build_burner_drill.hint", "3 gears, a stone furnace and 3 iron plates. Put it on an ore field – it mines the 3×3 blocks below and runs on coal (150 kW). Right-click it: coal goes into the fuel slot.");
            add("craftorio.quest.build_conveyor_belt", "Build a conveyor belt");
            add("craftorio.quest.build_conveyor_belt.hint", "1 gear and 1 iron plate make 2 belts. Belts carry items from the drill to the furnace.");
            add("craftorio.quest.build_boiler", "Build a boiler");
            add("craftorio.quest.build_boiler.hint", "A stone furnace and 4 pipes. The boiler burns coal into steam (1.8 MW) and needs an offshore pump next to it.");
            add("craftorio.quest.build_offshore_pump", "Build an offshore pump");
            add("craftorio.quest.build_offshore_pump.hint", "2 circuits, a pipe and a gear. Place it at the shore, next to the boiler: it pumps the water the boiler needs.");
            add("craftorio.quest.build_steam_engine", "Build a steam engine");
            add("craftorio.quest.build_steam_engine.hint", "8 gears, 5 pipes and 10 iron plates. Put it next to the boiler (one boiler runs two engines); each engine makes 900 kW.");
            add("craftorio.quest.build_power_pole", "Build power poles");
            add("craftorio.quest.build_power_pole.hint", "A log (from a wood field) and 2 copper cables make 2 poles. Poles connect generators and machines within their range into one grid.");
            add("craftorio.quest.build_laboratory", "Build a laboratory");
            add("craftorio.quest.build_laboratory.hint", "10 circuits, 10 gears and 4 belts. The laboratory turns science packs into research; connect it to power.");
            add("craftorio.quest.build_red_science", "Build 10 red science packs");
            add("craftorio.quest.build_red_science.hint", "1 copper plate and 1 gear each. Put them into the laboratory and start a research in the terminal.");
            add("craftorio.quest.build_inserter", "Build an inserter");
            add("craftorio.quest.build_inserter.hint", "1 circuit, 1 gear and 1 iron plate. Inserters move items between belts, machines and chests.");
            add("craftorio.quest.build_trading_post", "Build a trading post");
            add("craftorio.quest.build_trading_post.hint", "16 planks and 4 iron plates. Selling at the trading post earns credits – they pay for tower defense upgrades.");
            add("craftorio.quest.first_sale", "Sell something for the first time");
            add("craftorio.quest.first_sale.hint", "Put ore or plates into the trading post and press Sell.");
            add("craftorio.quest.unlock_assembler", "Research automation");
            add("craftorio.quest.unlock_assembler.hint", "Automation (10 red science packs) unlocks the assembling machine. Build laboratory and red packs first, then queue it in the terminal.");
            add("craftorio.quest.build_assembler", "Build an assembling machine");
            add("craftorio.quest.build_assembler.hint", "3 circuits, 5 gears and 9 iron plates. Pick a recipe with the arrows; it crafts with 75 kW at half the speed of a human hand… but never stops.");
            add("craftorio.quest.build_arena_gate", "Build an arena gate");
            add("craftorio.quest.build_arena_gate.hint", "8 iron plates, 8 stone bricks (smelt 16 stone in a stone furnace) and 2 circuits. Place it and right-click it: it takes you to your own arena. There, lay a path from the open gate in the west wall to the core in the east wall with the path wand.");
            add("craftorio.quest.build_crossbow_tower", "Build a crossbow tower");
            add("craftorio.quest.build_crossbow_tower.hint", "12 planks, 6 iron plates and 4 gears. Place it in your arena on open ground next to the path and load it with bolts.");
            add("craftorio.quest.unlock_arena_feeder", "Research turrets");
            add("craftorio.quest.unlock_arena_feeder.hint", "Turrets (10 red science packs) unlock the gun turret, ammunition and the arena feeder.");
            add("craftorio.quest.build_arena_feeder", "Build an arena feeder");
            add("craftorio.quest.build_arena_feeder.hint", "Nothing can be built inside the arena, so towers get power and ammunition from the outside: place the arena feeder in your factory, connect it to the power grid and feed it bolts and cartridges by belt or inserter. The arena HUD shows what has arrived.");
            add("craftorio.quest.unlock_cave_entrance", "Research the cave access");
            add("craftorio.quest.unlock_cave_entrance.hint", "Cave access (100 red packs, needs engines and a drill core from tower defense level 10) unlocks the cave entrance.");
            add("craftorio.quest.build_cave_entrance", "Build the cave entrance");
            add("craftorio.quest.build_cave_entrance.hint", "Build it on the surface (y ≥ 50), then deliver the required materials; the shaft drills down into the caves.");
            add("craftorio.quest.unlock_elevator", "Research cargo elevators");
            add("craftorio.quest.unlock_elevator.hint", "Cargo elevators (50 red packs) carry items between the layers.");
            add("craftorio.quest.unlock_mine_shaft", "Research the mine shaft");
            add("craftorio.quest.unlock_mine_shaft.hint", "Mine shaft (300 red packs, needs the deep core from tower defense level 30) unlocks the way to the mines.");
            add("craftorio.quest.mine_oak_log", "Mine 10 wood");
            add("craftorio.quest.mine_oak_log.hint", "Wood fields are ore fields of logs that never run out: mine one by hand or put a drill on it. You need wood for power poles.");
            add("craftorio.quest.build_terminal", "Build a terminal");
            add("craftorio.quest.build_terminal.hint", "5 iron plates and 2 circuits. The terminal is where you queue researches, collect guide rewards and control tower defense.");
            add("craftorio.research.logistics", "Logistics");
            add("craftorio.research.fast_inserters", "Fast Inserters");
            add("craftorio.splitter.filter_set", "Splitter filter: %s goes %s, everything else alternates between the other outputs");
            add("craftorio.splitter.filter_cleared", "Splitter filter cleared");
            add("craftorio.splitter.no_filter", "No filter: right-click with an item to set one");
            add("craftorio.splitter.output.front", "straight on");
            add("craftorio.splitter.output.left", "to the left");
            add("craftorio.splitter.output.right", "to the right");
            add("craftorio.hint.belt.1", "Slope");
            add("craftorio.hint.underground.1", "Exit in line, max. 4 blocks");
            add("craftorio.hint.splitter.1", "Set filter (item in hand)");
            add("craftorio.hint.splitter.2", "Filter direction (empty hand)");
            add("craftorio.hint.splitter.3", "Clear filter");
            add("craftorio.hint.filter_inserter.1", "Set filter (item in hand)");
            add("craftorio.hint.filter_inserter.2", "Clear filter");
            add("craftorio.hint.path_wand.1", "Lay path / line");
            add("craftorio.hint.path_wand.2", "Remove path");
            add("craftorio.hint.path_wand.3", "Show route (into air)");
            add("craftorio.hint.guide.1", "Handbook");
            add("craftorio.inserter.filter_set", "Filter: only %s");
            add("craftorio.inserter.filter_cleared", "Filter cleared");
            add("craftorio.inserter.no_filter", "No filter set: hold an item and right-click");
            add("craftorio.quest.unlock_underground_belt", "Research logistics");
            add("craftorio.quest.unlock_underground_belt.hint", "Logistics (75 red packs) unlocks the underground belt and the splitter. An underground belt is two pieces: place the second one in line up to 4 blocks after the first and it becomes the exit.");
            add("craftorio.quest.build_splitter", "Build a splitter");
            add("craftorio.quest.build_splitter.hint", "5 circuits, 5 iron plates and 4 belts. Feed it from behind: items alternate between front, left and right. Items alternate between the connected outputs. Right-click with an item sets a filter, right-click with an empty hand chooses where the filtered item goes, sneak + right-click clears the filter.");
            add("block.craftorio.underground_belt", "Underground Belt");
            add("block.craftorio.fast_underground_belt", "Fast Underground Belt");
            add("block.craftorio.splitter", "Splitter");
            add("block.craftorio.fast_splitter", "Fast Splitter");
            add("block.craftorio.long_inserter", "Long Inserter");
            add("block.craftorio.fast_inserter", "Fast Inserter");
            add("block.craftorio.filter_inserter", "Filter Inserter");
            add("craftorio.quest.next", "Next");
            add("craftorio.hud.guide", "Guide: %s");
            add("craftorio.hud.guide_done", "Guide: %s ✔ – press G to collect");
            add("craftorio.quest.claim", "Collect");
            add("craftorio.quest.done", "Done ✔");
            add("craftorio.quest.ready", "Reached!");
            add("craftorio.quest.open", "Not done yet");
            add("craftorio.quest.not_done", "This goal is not reached yet.");
            add("craftorio.quest.claimed", "Guide: %s – %s collected");
        }
    }

    public static final class German extends LanguageProvider {
        public German(PackOutput output) {
            super(output, Craftorio.MOD_ID, "de_de");
        }

        @Override
        protected void addTranslations() {
            add("itemGroup." + Craftorio.MOD_ID, "Craftorio");
            add(ModBlocks.CAP_ROCK.get(), "Deckgestein");
            add(ModBlocks.TRADING_POST.get(), "Handelsposten");
            add(ModBlocks.IRON_ORE_FIELD.get(), "Eisenerzfeld");
            add(ModBlocks.COPPER_ORE_FIELD.get(), "Kupfererzfeld");
            add(ModBlocks.COAL_FIELD.get(), "Kohlefeld");
            add(ModBlocks.BURNER_DRILL.get(), "Brenner-Bohrer");
            add(ModBlocks.CONVEYOR_BELT.get(), "Förderband");
            add(ModBlocks.INSERTER.get(), "Greifarm");

            add(ModBlocks.BOILER.get(), "Kessel");
            add(ModBlocks.STEAM_ENGINE.get(), "Dampfmaschine");
            add(ModBlocks.OFFSHORE_PUMP.get(), "Offshore-Pumpe");
            add(ModBlocks.STONE_FIELD.get(), "Steinfeld");
            add(ModBlocks.WOOD_FIELD.get(), "Holzfeld");
            add(ModItems.PIPE.get(), "Rohr");
            add(ModItems.STONE_BRICK.get(), "Steinziegel");
            add(ModBlocks.POWER_POLE.get(), "Strommast");
            add(ModBlocks.ELECTRIC_FURNACE.get(), "Elektro-Schmelzofen");
            add(ModBlocks.STONE_FURNACE.get(), "Steinofen");
            add(ModBlocks.ASSEMBLER.get(), "Montagemaschine 1");
            add(ModItems.COPPER_CABLE.get(), "Kupferkabel");
            add(ModItems.IRON_GEAR.get(), "Zahnrad");
            add(ModItems.CIRCUIT.get(), "Schaltkreis");
            add(ModItems.MOTOR.get(), "Motor");
            add(ModItems.STEEL_PLATE.get(), "Stahlplatte");
            add(ModItems.IRON_STICK.get(), "Eisenstange");
            add(ModBlocks.MEDIUM_POWER_POLE.get(), "Mittlerer Strommast");
            add(ModBlocks.SOLAR_PANEL.get(), "Solarpanel");
            add(ModBlocks.STEEL_FURNACE.get(), "Stahlofen");
            add(ModBlocks.ASSEMBLER_2.get(), "Montagemaschine 2");
            add("craftorio.solar.output", "Solarpanel: %s von %s kW");
            add("craftorio.solar.no_sky", "Das Solarpanel braucht freien Himmel");
            add("craftorio.research.electronics", "Elektronik");
            add("craftorio.research.steel_processing", "Stahlverarbeitung");
            add("craftorio.research.logistic_science_pack", "Logistik-Wissenschaftspaket");
            add("craftorio.research.automation_2", "Automatisierung 2");
            add("craftorio.research.electric_energy_distribution_1", "Elektrische Energieverteilung 1");
            add("craftorio.research.advanced_material_processing", "Fortgeschrittene Materialverarbeitung");
            add("craftorio.research.solar_energy", "Solarenergie");

            add("craftorio.gui.energy", "Energie: %s / %s FE");
            add("craftorio.gui.no_recipe", "Rezept wählen");
            add("craftorio.power.no_network", "Nicht verbunden");
            add("craftorio.power.network", "Netz: %s Masten · %s Generatoren · %s Verbraucher · %s/%s FE/t · %s%% versorgt");

            add(ModBlocks.TERMINAL.get(), "Terminal");
            add(ModBlocks.WORKBENCH.get(), "Konstruktionswerkbank");
            add(ModItems.DRILL_CORE.get(), "Bohrkern");
            add(ModItems.RESONANCE_CRYSTAL.get(), "Resonanzkristall");
            add(ModItems.DEEP_CORE.get(), "Tiefenkern");
            add(ModItems.STAR_SHARD.get(), "Sternenerz-Splitter");

            add("craftorio.key_material.hint", "Schlüsselmaterial – Belohnung für Tower-Defense-Level %s");
            add("craftorio.workbench.hint", "Klick: 1 bauen · Shift-Klick: 10 bauen");
            add("craftorio.workbench.build", "Bauen");
            add("craftorio.workbench.can_build", "baubereit");
            add("craftorio.research.electric_smelting", "Elektrisches Schmelzen");
            add("craftorio.boiler.water", "Wasser: Pumpe verbunden");
            add("craftorio.boiler.no_water", "Kein Wasser: Offshore-Pumpe am Ufer neben den Kessel setzen");
            add("craftorio.steam_engine.status.0", "Läuft: 900 kW");
            add("craftorio.steam_engine.status.1", "Kein Kessel neben der Maschine");
            add("craftorio.steam_engine.status.3", "Bereit, aber niemand nimmt den Strom ab: Strommast und Verbraucher anschließen");
            add("craftorio.steam_engine.status.2", "Der Kessel hat keinen Dampf (Brennstoff oder Wasser fehlt, oder zwei Maschinen nutzen ihn schon)");
            add("craftorio.workbench.locked", "Forschung nötig");
            add("craftorio.workbench.missing", "Material fehlt");
            add("craftorio.terminal.tab.stats", "Statistik");
            add("craftorio.research.automation", "Automatisierung");
            add("craftorio.research.turrets", "Geschütztürme");
            add("craftorio.research.gun_turrets", "Maschinengewehrtürme");
            add("craftorio.research.energy_turrets", "Energietürme");
            add("craftorio.research.engines", "Motoren");
            add("craftorio.research.caves", "Höhlenzugang");
            add("craftorio.research.elevators", "Warenaufzüge");
            add("craftorio.research.fast_belts", "Schnelle Bänder");
            add("craftorio.research.mine_shaft", "Minenschacht");
            add("craftorio.research.deep_mining", "Tiefbergbau");
            add("craftorio.research.express_belts", "Expressbänder");
            add("craftorio.research.nuclear_power", "Kernkraft");
            add("craftorio.research.laser_turrets", "Laserschütztürme");
            add("craftorio.terminal.tab.research", "Forschung");
            add("craftorio.research.queue", "Erforschen");
            add("craftorio.terminal.stats.research", "Abgeschlossene Forschungen (Weltzeit)");
            add("craftorio.research.remove", "Entfernen");
            add("craftorio.research.status.done", "erforscht");
            add("craftorio.research.status.active", "läuft: %s / %s Einheiten");
            add("craftorio.research.status.queued", "in der Warteschlange (Platz %s)");
            add("craftorio.research.status.locked", "braucht %s");
            add("craftorio.research.cost", "Kosten: %s");
            add("craftorio.research.requires", "Voraussetzung:");
            add("craftorio.research.unlocks", "Schaltet frei:");
            add("craftorio.research.key_items", "Wird beim Start einmal abgegeben:");
            add("craftorio.research.locked", "Erst die Voraussetzungen erforschen oder einreihen");
            add("craftorio.research.missing_key_items", "Du brauchst das Schlüsselmaterial im Inventar");
            add("craftorio.research.finished", "Forschung abgeschlossen: %s");
            add("craftorio.lab.status.0", "Bereit");
            add("craftorio.lab.status.1", "Gehört keinem Team");
            add("craftorio.lab.status.2", "Keine Forschung gewählt");
            add("craftorio.lab.status.3", "Wissenschaftspakete fehlen");
            add("craftorio.lab.status.4", "Forscht");
            add("craftorio.lab.status.5", "Kein Strom");
            add("craftorio.guide.research_then_build", "%s im Terminal erforschen, dann an der %s bauen aus:");
            add("craftorio.emi.research", "Forschung: %s");
            add(ModBlocks.LABORATORY.get(), "Labor");
            add(ModItems.RED_SCIENCE.get(), "Automatisierungspaket (rot)");
            add(ModItems.GREEN_SCIENCE.get(), "Logistikpaket (grün)");
            add(ModItems.MILITARY_SCIENCE.get(), "Militärpaket (grau)");
            add(ModItems.BLUE_SCIENCE.get(), "Chemiepaket (blau)");
            add("craftorio.terminal.stats.earned", "Gesamt eingenommen");
            add("craftorio.terminal.stats.spent", "Gesamt ausgegeben");
            add("craftorio.terminal.stats.recent", "Eingenommen in den letzten 10 Minuten");
            add("craftorio.terminal.stats.top", "Meistverkauft");
            add("craftorio.blueprint.materials", "Material:");
            add("craftorio.blueprint.locked", "Für dieses Rezept fehlt eine Forschung");

            add(ModBlocks.ZONE_CORE.get(), "Zonenkern");
            add(ModBlocks.ENEMY_PORTAL.get(), "Feindportal");
            add(ModBlocks.PATH_BLOCK.get(), "Pfadblock");
            add(ModBlocks.CROSSBOW_TOWER.get(), "Armbrustturm");
            add(ModBlocks.GUN_TURRET.get(), "Geschützturm");
            add(ModBlocks.TESLA_TOWER.get(), "Tesla-Turm");
            add(ModBlocks.TOWER_RUIN.get(), "Turmruine");
            add(ModItems.BOLT.get(), "Bolzen");
            add(ModItems.CARTRIDGE.get(), "Patrone");
            add("entity.craftorio.crawler", "Krabbler");
            add("entity.craftorio.breaker", "Brecher");
            add("entity.craftorio.spitter", "Spucker");
            add("entity.craftorio.brood_mother", "Brutmutter");

            add("craftorio.terminal.tab.defense", "Abwehr");
            add("craftorio.hud.td", "Level %s · Welle %s/%s · Leben %s/%s · %s Gegner");
            add("craftorio.td.next_level", "Nächstes Level");
            add("craftorio.td.wave", "Welle");
            add("craftorio.td.lives", "Leben");
            add("craftorio.td.enemies", "Verbleibende Gegner");
            add("craftorio.td.reward", "Belohnung");
            add("craftorio.td.milestone", "Nächstes Schlüsselmaterial");
            add("craftorio.td.milestone.in", "in %s Leveln");
            add("craftorio.td.key_next", "Dieses Level bringt ein Schlüsselmaterial!");
            add("craftorio.td.rules", "Ein Level ist verloren, wenn %s Leben weg sind. Gegner greifen nur Türme an – die Fabrik bleibt sicher. Zerstörte Türme hinterlassen Ruinen, die du wieder aufbauen kannst.");
            add("craftorio.td.button.start", "Level %s starten");
            add("craftorio.td.button.auto_on", "Automatisch weiter: an");
            add("craftorio.td.button.auto_off", "Automatisch weiter: aus");
            add("craftorio.td.button.repair", "Alle Türme reparieren (%s)");
            add("craftorio.td.started", "Level %s gestartet!");
            add("craftorio.td.won", "Level %s geschafft! +%s");
            add("craftorio.td.lost", "Level %s verloren – repariere oder verbessere deine Türme und versuche es erneut.");
            add("craftorio.td.repair.nothing", "Nichts zu reparieren.");
            add("craftorio.td.repair.too_expensive", "Zu wenig Credits (%s nötig).");
            add("craftorio.td.repair.done", "Türme für %s repariert.");
            add("craftorio.td.error.no_zone", "Dein Team hat keine Verteidigungszone.");
            add("craftorio.td.error.running", "Es läuft bereits ein Level.");
            add("craftorio.td.error.no_portal", "In der Zone steht kein Feindportal.");
            add("craftorio.td.error.no_team", "Du bist in keinem Team.");
            add("craftorio.td.error.zone_exists", "Dein Team hat bereits einen Zonenkern.");
            add("craftorio.td.error.overworld_only", "Verteidigungszonen gibt es nur in der Oberwelt.");
            add("craftorio.td.error.outside_zone", "Nur innerhalb deiner Verteidigungszone (%s Blöcke um den Zonenkern).");
            add("craftorio.td.error.foreign_zone", "Dieser Zonenkern gehört einem anderen Team.");
            add("craftorio.td.error.path.no_start", "Neben dem Feindportal liegt kein Pfadblock.");
            add("craftorio.td.error.path.branch", "Der Pfad verzweigt sich – er muss eine einzige Linie sein.");
            add("craftorio.td.error.path.dead_end", "Der Pfad endet, bevor er den Zonenkern erreicht.");
            add("craftorio.td.error.path.too_short", "Der Pfad ist zu kurz (mindestens %s Blöcke).");
            add("craftorio.td.error.path.too_long", "Der Pfad ist zu lang.");
            add("craftorio.tower.upgrade", "Aufrüsten");
            add("craftorio.tower.level", "Stufe %s");
            add("craftorio.tower.upgraded", "Turm auf Stufe %s aufgerüstet für %s");
            add("craftorio.tower.rebuilt", "Turm für %s wieder aufgebaut");

            add(ModBlocks.CAVE_RUBBLE.get(), "Höhlengeröll");
            add(ModBlocks.CAVE_ENTRANCE.get(), "Höhleneingang");
            add(ModBlocks.TIN_ORE_FIELD.get(), "Zinnerzfeld");
            add(ModBlocks.LEAD_ORE_FIELD.get(), "Bleierzfeld");
            add(ModBlocks.SULFUR_FIELD.get(), "Schwefelfeld");
            add(ModBlocks.GOLD_ORE_FIELD.get(), "Golderzfeld");
            add(ModBlocks.QUARTZ_FIELD.get(), "Quarzfeld");
            add(ModItems.RAW_TIN.get(), "Rohzinn");
            add(ModItems.TIN_INGOT.get(), "Zinnbarren");
            add(ModItems.RAW_LEAD.get(), "Rohblei");
            add(ModItems.LEAD_INGOT.get(), "Bleibarren");
            add(ModItems.SULFUR.get(), "Schwefel");
            add(ModItems.BATTERY.get(), "Batterie");
            add(ModItems.ADVANCED_CIRCUIT.get(), "Fortgeschrittener Schaltkreis");
            add(ModBlocks.ELEVATOR.get(), "Warenaufzug");
            add("craftorio.elevator.mode.receive", "Modus: empfangen (Ausgabe nach vorne)");
            add("craftorio.elevator.mode.send_up", "Modus: nach oben senden");
            add("craftorio.elevator.mode.send_down", "Modus: nach unten senden");
            add("craftorio.elevator.target", "→ Gegenstück %s Blöcke entfernt");
            add("craftorio.elevator.no_target", "→ kein Aufzug in dieser Spalte!");
            add("craftorio.cave.needs", "Baustelle braucht noch:");
            add("craftorio.cave.drilling", "Bohrung: %s%% (braucht %s FE/t über einen Strommast)");
            add("craftorio.cave.open", "Höhleneingang offen – über das Gerüst hinab (Schleichen zum Absteigen).");
            add("craftorio.cave.opened", "Ein Höhleneingang wurde geöffnet! Der Höhlenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.cave.error.overworld_only", "Höhleneingänge gibt es nur in der Oberwelt.");
            add("craftorio.cave.error.too_deep", "Höhleneingänge an der Oberfläche bauen (ab Y 50).");
            add("craftorio.cave.error.no_layer", "Unter dieser Stelle gibt es keine Höhlenschicht (Gebiet vor dem Höhlen-Update erzeugt).");

            add("craftorio.drill.status", "Bohrer: %s/%s Feldblöcke · %s Items/s · Brennstoff für %s s");
            add("craftorio.drill.gui_fields", "Feldblöcke: %s/%s");
            add("craftorio.drill.gui_rate", "%s Items/s");
            add("craftorio.drill.gui_no_field", "Auf ein Erzfeld setzen!");
            add("craftorio.drill.overlap", "Zu nah an einem anderen Bohrer – Abbauflächen dürfen sich nicht überlappen.");
            add(ModBlocks.MINE_RUBBLE.get(), "Minengeröll");
            add(ModBlocks.MINE_SHAFT.get(), "Minenschacht");
            add(ModBlocks.DIAMOND_FIELD.get(), "Diamantfeld");
            add(ModBlocks.TITANIUM_ORE_FIELD.get(), "Titanerzfeld");
            add(ModBlocks.URANIUM_ORE_FIELD.get(), "Uranerzfeld");
            add(ModBlocks.CRYSTAL_FIELD.get(), "Kristallfeld");
            add(ModItems.RAW_TITANIUM.get(), "Roh-Titan");
            add(ModItems.TITANIUM_INGOT.get(), "Titanbarren");
            add(ModItems.TITANIUM_PLATE.get(), "Titanplatte");
            add(ModItems.RAW_URANIUM.get(), "Roh-Uran");
            add(ModItems.URANIUM_PELLET.get(), "Uranpellet");
            add(ModItems.CRYSTAL_SHARD.get(), "Kristallsplitter");
            add(ModItems.ENERGY_CRYSTAL.get(), "Energiekristall");
            add(ModItems.FUEL_ROD.get(), "Brennstab");
            add(ModBlocks.ELECTRIC_DRILL.get(), "Elektrischer Bohrer");
            add(ModBlocks.DEEP_DRILL.get(), "Tiefenbohrer");
            add(ModBlocks.FAST_BELT.get(), "Schnelles Förderband");
            add(ModBlocks.EXPRESS_BELT.get(), "Express-Förderband");
            add(ModBlocks.REACTOR.get(), "Reaktor");
            add(ModBlocks.LASER_TOWER.get(), "Laserturm");
            add("entity.craftorio.crystal_golem", "Kristallgolem");
            add("craftorio.command.layer_unlocked", "%s Chunks der Schicht freigeschaltet (Y %s bis %s); sie werden ausgehöhlt.");
            add("craftorio.mine.open", "Minenschacht offen – über das Gerüst hinab in die Minenschicht.");
            add("craftorio.mine.opened", "Ein Minenschacht wurde geöffnet! Der Minenbereich um Chunk %s, %s wird ausgehöhlt.");
            add("craftorio.mine.error.not_in_caves", "Minenschächte in einem freigeschalteten Bereich der Höhlenschicht bauen (Y 0 bis 39).");
            add("craftorio.drill.status_electric", "Bohrer: %s/%s Feldblöcke · %s Items/s · %s FE gespeichert (braucht %s FE/t)");

            add("craftorio.tooltip.sell_price", "Verkaufswert: %s");
            add("craftorio.tooltip.sell_price_stack", "Verkaufswert: %s (Stapel: %s)");
            add("craftorio.trading_post.sold", "Verkauft für %s");
            add("craftorio.trading_post.info", "Handelsposten von Team %s – bisher eingenommen: %s");
            add("craftorio.trading_post.value", "Wert: %s");
            add("craftorio.trading_post.sell", "Verkaufen");
            add("craftorio.trading_post.owner", "Team: %s");
            add("craftorio.trading_post.earned", "Gesamt: %s");

            add("craftorio.command.credits", "Team %s hat %s");
            add("craftorio.command.team.info", "Team %s – Kontostand: %s – Mitglieder: %s");
            add("craftorio.command.team.list_entry", "%s (%s Mitglieder)");
            add("craftorio.command.team.created", "Team %s gegründet.");
            add("craftorio.command.team.invited", "%s hat dich in Team %s eingeladen.");
            add("craftorio.command.team.invite_sent", "Einladung an %s gesendet.");
            add("craftorio.command.team.joined", "Du bist Team %s beigetreten.");
            add("craftorio.command.team.left", "Du hast dein Team verlassen und spielst jetzt als Team %s.");

            add("craftorio.team.error.name_taken", "Ein Team namens %s existiert bereits.");
            add("craftorio.team.error.invalid_name", "Teamnamen müssen 1–%s Zeichen lang sein: Buchstaben, Ziffern, Leerzeichen, _ und -.");
            add("craftorio.team.error.no_team", "Du bist in keinem Team.");
            add("craftorio.team.error.already_member", "Dieser Spieler ist bereits in diesem Team.");
            add("craftorio.team.error.unknown_team", "Es gibt kein Team namens %s.");
            add("craftorio.team.error.not_invited", "Du wurdest nicht in Team %s eingeladen.");
            add("craftorio.team.error.alone", "Du bist das einzige Mitglied deines Teams.");
            add("craftorio.command.team.rights", "Leitung: %s – Ausgaben: %s");
            add("craftorio.command.team.spending.all", "alle Mitglieder");
            add("craftorio.command.team.spending.leader", "nur Leitung");
            add("craftorio.command.team.spending.set_all", "Alle Mitglieder dürfen jetzt Credits des Teams ausgeben.");
            add("craftorio.command.team.spending.set_leader", "Nur noch die Teamleitung darf Credits ausgeben.");
            add("craftorio.command.team.kicked", "%s wurde aus dem Team entfernt.");
            add("craftorio.command.team.kicked_you", "Du wurdest aus Team %s entfernt und spielst jetzt in deinem eigenen Team.");
            add("craftorio.command.team.new_leader", "%s leitet jetzt das Team.");
            add("craftorio.team.error.not_leader", "Das darf nur die Teamleitung.");
            add("craftorio.team.error.not_member", "Dieser Spieler ist nicht in deinem Team.");
            add("craftorio.team.error.kick_self", "Du kannst dich nicht selbst entfernen – nutze /craftorio team leave.");
            add("craftorio.team.error.no_spend_permission", "Nur deine Teamleitung darf Credits ausgeben.");
            add("craftorio.team.error.one_player", "Gib genau einen Spieler an.");
            add("craftorio.protection.denied", "Das gehört Team %s.");
            add("craftorio.protection.too_close", "Zu nah an Team %s – halte einen Block Abstand zu deren Maschinen und Behältern.");
            add("emi.category.craftorio.pressing", "Pressen");
            add("emi.category.craftorio.assembling", "Montage");
            add("emi.category.craftorio.blueprint", "Bauplan (Werkbank)");
            add("craftorio.emi.time", "%s s");
            add("craftorio.emi.free", "kostenlos");
            add("config.jade.plugin_craftorio.status", "Craftorio-Status");
            add("config.jade.plugin_craftorio.ore_field", "Craftorio-Erzfelder");
            add("craftorio.jade.owner", "Besitzer: Team %s");
            add("craftorio.jade.progress", "Fortschritt: %s%%");
            add("craftorio.jade.tower", "HP %s / %s · Stufe %s");
            add("craftorio.jade.ammo", "Munition: %s");
            add("craftorio.jade.ruin", "Zerstört – Wiederaufbau für %s");
            add("craftorio.jade.ore_field", "Liefert %s (je %s) – unerschöpflich");
            add("craftorio.terminal.tab.quests", "Leitfaden");
            add("craftorio.workbench.missing_button", "Fehlt?");
            add("craftorio.workbench.missing_list", "Für %s fehlt noch:");
            add("craftorio.workbench.have", " (du hast %s)");
            add("craftorio.toast.goal", "Erreicht! Mit G abholen");
            add("craftorio.starter_kit", "Willkommen bei Craftorio! Dein Starter-Kit: das Handbuch (Taste G), eine Starter-Spitzhacke für Erzfelder und Stein, eine Konstruktionswerkbank und Kohle. Fang damit an, Eisenerz per Hand abzubauen – das Handbuch zeigt jeden Schritt.");
            add(ModItems.GUIDE_BOOK.get(), "Craftorio-Handbuch");
            add(ModItems.STARTER_PICKAXE.get(), "Starter-Spitzhacke");
            add("key.craftorio.guide", "Handbuch öffnen");
            add("key.categories.craftorio", "Craftorio");
            add("craftorio.guide.current", "Aktuell");
            add("craftorio.guide.claim", "Belohnung abholen");
            add("craftorio.guide.step", "Leitfaden · Schritt %s von %s");
            add("craftorio.guide.progress", "Fortschritt: %s");
            add("craftorio.guide.reward", "Belohnung: %s");
            add("craftorio.guide.build_at", "Bauen an der %s aus:");
            add("craftorio.guide.crafting", "Rezept: %s");
            add("craftorio.guide.vanilla_table", "(normale Werkbank)");
            add("craftorio.guide.value", "Verkaufswert: %s pro Stück");
            add("craftorio.guide.mined_from", "Abbau am %s – per Bohrer oder von Hand");
            add("craftorio.guide.made_in", "Hergestellt in der %s aus:");
            add("craftorio.guide.smelted", "Geschmolzen im Ofen oder Elektroofen:");
            add("craftorio.guide.earn", "Verkaufe verarbeitete Waren: je mehr Verarbeitungsschritte, desto höher der Preis. Die Statistik im Terminal zeigt, was sich am meisten lohnt.");
            add("craftorio.guide.defense", "Tower Defense: geh durch dein Arena-Tor, lege mit dem Pfadstab einen Weg vom offenen Tor zum Kern, stelle Türme daneben und starte das Level im Terminal (Tab Abwehr).");
            add("craftorio.hud.guide_key", "[%s] Handbuch");
            add("craftorio.hud.supply", "Arena-Versorgung: %s FE · %s Bolzen · %s Patronen");
            add("craftorio.hud.unsupplied", "%s Turm/Türme ohne Versorgung! Baue einen Arena-Einspeiser in deiner Fabrik.");
            add("craftorio.tooltip.tower.energy", "Läuft mit Strom: Versorgung über den Arena-Einspeiser in deiner Fabrik.");
            add("craftorio.tooltip.tower.ammo", "Von Hand laden oder Munition über den Arena-Einspeiser in deiner Fabrik liefern.");
            add("craftorio.tooltip.arena_feeder", "Steht in deiner Fabrik: speist Strom und Munition in die Arena ein, aus der die Türme sich bedienen.");
            add("craftorio.arena.error.overworld_only", "Arena-Tore funktionieren nur in der Oberwelt.");
            add("craftorio.arena.error.not_arena", "Nur in deiner Arena.");
            add("craftorio.arena.error.outside_field", "Nur innerhalb des Arenafelds.");
            add("craftorio.arena.error.foreign", "Das ist die Arena eines anderen Teams.");
            add("craftorio.arena.error.no_tower_here", "Türme stehen nur auf freiem Boden oder auf einem Plateau – nicht auf dem Weg, Bäumen, Fels, Wasser oder Lava.");
            add("craftorio.arena.error.no_building", "Die Arena lässt sich nicht verändern – lege den Weg mit dem Pfadstab und stelle Türme auf.");
            add("craftorio.arena.path.blocked", "Dort kann der Weg nicht entlangführen.");
            add("craftorio.arena.path.route_hint", "Die grünen Partikel zeigen den kürzesten Weg vom Tor zum Kern.");
            add("craftorio.arena.path.branch", "Der Weg muss eine einzelne Linie bleiben: keine Abzweigungen, Kreuzungen oder 2x2-Flächen.");
            add("craftorio.arena.path_wand.tooltip", "Klick auf den Arenaboden legt Weg; der nächste Klick in derselben Reihe oder Spalte zieht eine gerade Linie. Schleichen + Klick entfernt Weg oder beginnt eine neue Linie; Schleichen + Klick in die Luft zeigt den kürzesten Weg.");
            add("craftorio.arena.welcome", "Arena · Level %s · Karte: %s – %s");
            add("craftorio.arena.new_map", "Die Arena hat sich verändert: neue Karte %s. Deine Türme warten im Turmdepot – lege einen neuen Weg!");
            add("craftorio.arena.old_core", "Verteidigungszonen sind jetzt Arenen – baue ein Arena-Tor (Gratis-Bauplan) und geh hindurch.");
            add("craftorio.arena.theme.forest", "Wald");
            add("craftorio.arena.theme.forest.rule", "Gegner im Dickicht sind getarnt: Türme erkennen sie nur auf halbe Reichweite.");
            add("craftorio.arena.theme.mountain", "Berge");
            add("craftorio.arena.theme.mountain.rule", "Türme auf Plateaus reichen 30 % weiter; Geröll bremst Gegner.");
            add("craftorio.arena.theme.fire", "Feuer");
            add("craftorio.arena.theme.fire.rule", "Lavaschlote brechen alle paar Sekunden aus und verbrennen Gegner, die darüber laufen.");
            add("craftorio.arena.theme.water", "Wasser");
            add("craftorio.arena.theme.water.rule", "Der Fluss ist nur an Furten passierbar; Flachwasser bremst Gegner stark.");
            add("craftorio.arena.theme.colosseum", "Kolosseum");
            add("craftorio.arena.theme.colosseum.rule", "Boss-Level: offener Sand zwischen Säulen.");
            add("craftorio.arena.mutator.fog", "Mutator Nebel: Türme sehen 25 % weniger weit (+25 % Belohnung).");
            add("craftorio.arena.mutator.haste", "Mutator Eilmarsch: Gegner sind 30 % schneller (+25 % Belohnung).");
            add("craftorio.arena.mutator.hardened", "Mutator Gehärtet: Gegner haben 35 % mehr Leben (+30 % Belohnung).");
            add("craftorio.arena.depot.empty", "Das Turmdepot ist leer.");
            add("craftorio.arena.depot.take_all", "Alles nehmen");
            add("craftorio.arena.depot.taken", "%s Stapel aus dem Turmdepot genommen.");
            add("craftorio.arena.feeder.status", "Arena-Vorrat: %s / %s FE · %s Bolzen · %s Patronen");
            add("craftorio.arena.feeder.no_owner", "Dieser Einspeiser gehört keinem Team.");
            add("craftorio.arena.feeder.no_arena", "Dein Team hat noch keine Arena – geh zuerst durch ein Arena-Tor.");
            add("craftorio.td.error.not_running", "Es läuft kein Level.");
            add("craftorio.td.call.not_now", "Die nächste Welle lässt sich nur zwischen zwei Wellen rufen.");
            add("craftorio.td.call.done", "Nächste Welle früher gerufen! +%s");
            add("craftorio.td.won_stars", "Level %s geschafft %s! +%s");
            add("craftorio.td.button.call", "Welle rufen");
            add("craftorio.td.map", "Karte");
            add("craftorio.td.last_stars", "Letztes Level");
            add("craftorio.td.preview", "Nächste Welle:");
            add("craftorio.td.reserves", "Arena-Vorrat: %s FE · %s Bolzen · %s Patronen");
            add("craftorio.tower.target.first", "Ziel: Erster");
            add("craftorio.tower.target.last", "Ziel: Letzter");
            add("craftorio.tower.target.strongest", "Ziel: Stärkster");
            add("craftorio.tower.target.weakest", "Ziel: Schwächster");
            add("craftorio.td.help", "Noch keine Arena. Baue ein Arena-Tor (Gratis-Bauplan), stelle es in der Oberwelt auf und rechtsklicke es. Lege in deiner Arena mit dem Pfadstab einen Weg vom offenen Gegnertor zum Kern und stelle Türme auf freien Boden. Jedes geschaffte Level bringt eine neue Karte.");
            add("craftorio.td.key_reward", "Schlüsselmaterial %s wartet im Turmdepot!");
            add("craftorio.td.path_ok", "Weg OK: %s Blöcke vom Tor bis zum Kern.");
            add(ModBlocks.ARENA_BASE.get(), "Arenaboden");
            add(ModBlocks.ARENA_CLIFF.get(), "Plateaufels");
            add(ModBlocks.ARENA_GATE.get(), "Arena-Tor");
            add(ModBlocks.ARENA_EXIT.get(), "Arena-Ausgang");
            add(ModBlocks.TOWER_DEPOT.get(), "Turmdepot");
            add(ModBlocks.ARENA_CONSOLE.get(), "Arena-Pult");
            add(ModBlocks.ARENA_FEEDER.get(), "Arena-Einspeiser");
            add(ModItems.PATH_WAND.get(), "Pfadstab");
            add("craftorio.quest.earn_10k", "Verdiene insgesamt 10.000 ¢");
            add("craftorio.quest.earn_10k.hint", "Erweitere: mehr Bohrer, mehr Felder, mehr Verarbeitung. Der Tab Statistik zeigt, was am meisten einbringt.");
            add("craftorio.quest.td_1", "Schaffe Tower-Defense-Level 1");
            add("craftorio.quest.td_1.hint", "Starte das Level im Terminal-Tab Abwehr. Gegner greifen nur Türme an – deine Fabrik ist nie in Gefahr. Jedes geschaffte Level bringt eine neue Karte: hol deine Türme aus dem Turmdepot.");
            add("craftorio.quest.td_10", "Schaffe Tower-Defense-Level 10");
            add("craftorio.quest.td_10.hint", "Level 10 belohnt mit dem Bohrkern – dem Schlüssel zur Werkbank der Stufe 2. Rüste Türme zwischen den Levels auf und repariere sie.");
            add("craftorio.quest.sell_tin_ingot", "Verkaufe 64 Zinnbarren");
            add("craftorio.quest.sell_tin_ingot.hint", "Zinn-, Blei-, Schwefel-, Gold- und Quarzfelder liegen auf dem Höhlenboden. Bring Strom nach unten und baue dort Bohrer auf.");
            add("craftorio.quest.sell_battery", "Verkaufe 32 Batterien");
            add("craftorio.quest.sell_battery.hint", "Batterien entstehen aus Blei, Schwefel und Kabeln – ein Höhlenprodukt, viel mehr wert als seine Teile.");
            add("craftorio.quest.td_20", "Schaffe Tower-Defense-Level 20");
            add("craftorio.quest.td_20.hint", "Ab Level 20 kommen Kristallgolems – nur Energietürme (Tesla, Laser) schaden ihnen voll.");
            add("craftorio.quest.td_30", "Schaffe Tower-Defense-Level 30");
            add("craftorio.quest.td_30.hint", "Level 30 belohnt mit dem Tiefenkern – dem Schlüssel zur Präzisionswerkbank (Stufe 3).");
            add("craftorio.quest.sell_titanium_plate", "Verkaufe 64 Titanplatten");
            add("craftorio.quest.sell_titanium_plate.hint", "Schmelze Roh-Titan und presse die Barren. Tiefenbohrer (5×5) holen am meisten aus den Minenfeldern.");
            add("craftorio.quest.sell_energy_crystal", "Verkaufe 8 Energiekristalle");
            add("craftorio.quest.sell_energy_crystal.hint", "Energiekristalle vereinen Kristallsplitter, einen fortgeschrittenen Schaltkreis und eine Batterie – die bisher wertvollste Ware.");
            add("craftorio.quest.earn_1m", "Verdiene insgesamt 1.000.000 ¢");
            add("craftorio.quest.earn_1m.hint", "Baue alle drei Schichten aus. Reaktoren mit Brennstäben versorgen die größten Fabriken.");
            add("craftorio.quest.td_40", "Schaffe Tower-Defense-Level 40");
            add("craftorio.quest.td_40.hint", "Die bisher letzte Herausforderung: Lasertürme und aufgerüstete Tesla-Türme gegen gepanzerte Wellen.");
            add("craftorio.quest.mine_raw_iron", "Baue 16 Roheisen ab");
            add("craftorio.quest.mine_raw_iron.hint", "Baue das Eisenerzfeld in Spawn-Nähe mit der Starter-Spitzhacke von Hand ab.");
            add("craftorio.quest.mine_cobblestone", "Baue 20 Stein ab");
            add("craftorio.quest.mine_cobblestone.hint", "Steinfelder sind große Erzfelder aus Bruchstein; du brauchst Stein für Öfen und später für Ziegel.");
            add("craftorio.quest.build_stone_furnace", "Baue einen Steinofen");
            add("craftorio.quest.build_stone_furnace.hint", "Öffne die Konstruktionswerkbank (im Starterpaket) und baue den Steinofen aus 5 Stein. Kohle kommt in den Brennstoffslot, Erz in den Eingang: es wird zu Platten (Barren). Auch Steinziegel entstehen hier: mindestens 2 Stein hineinlegen (2 Stein → 1 Steinziegel, 3,2 s).");
            add("craftorio.quest.build_burner_drill", "Baue einen Brenner-Bohrer");
            add("craftorio.quest.build_burner_drill.hint", "3 Zahnräder, ein Steinofen und 3 Eisenplatten. Setze ihn auf ein Erzfeld – er baut die 3×3 Blöcke darunter ab und läuft mit Kohle (150 kW). Rechtsklick: Kohle kommt in den Brennstoffslot.");
            add("craftorio.quest.build_conveyor_belt", "Baue ein Förderband");
            add("craftorio.quest.build_conveyor_belt.hint", "1 Zahnrad und 1 Eisenplatte ergeben 2 Bänder. Bänder bringen Items vom Bohrer zum Ofen.");
            add("craftorio.quest.build_boiler", "Baue einen Kessel");
            add("craftorio.quest.build_boiler.hint", "Ein Steinofen und 4 Rohre. Der Kessel verbrennt Kohle zu Dampf (1,8 MW) und braucht eine Offshore-Pumpe neben sich.");
            add("craftorio.quest.build_offshore_pump", "Baue eine Offshore-Pumpe");
            add("craftorio.quest.build_offshore_pump.hint", "2 Schaltkreise, ein Rohr und ein Zahnrad. Stelle sie am Ufer neben den Kessel: Sie pumpt das Wasser, das der Kessel braucht.");
            add("craftorio.quest.build_steam_engine", "Baue eine Dampfmaschine");
            add("craftorio.quest.build_steam_engine.hint", "8 Zahnräder, 5 Rohre und 10 Eisenplatten. Stelle sie neben den Kessel (ein Kessel versorgt zwei Maschinen); jede liefert 900 kW.");
            add("craftorio.quest.build_power_pole", "Baue Strommasten");
            add("craftorio.quest.build_power_pole.hint", "Ein Stamm (vom Holzfeld) und 2 Kupferkabel ergeben 2 Masten. Masten verbinden Generatoren und Maschinen in Reichweite zu einem Netz.");
            add("craftorio.quest.build_laboratory", "Baue ein Labor");
            add("craftorio.quest.build_laboratory.hint", "10 Schaltkreise, 10 Zahnräder und 4 Bänder. Das Labor macht aus Wissenschaftspaketen Forschung; schließe es ans Stromnetz an.");
            add("craftorio.quest.build_red_science", "Baue 10 rote Wissenschaftspakete");
            add("craftorio.quest.build_red_science.hint", "Je 1 Kupferplatte und 1 Zahnrad. Lege sie ins Labor und starte im Terminal eine Forschung.");
            add("craftorio.quest.build_inserter", "Baue einen Greifarm");
            add("craftorio.quest.build_inserter.hint", "1 Schaltkreis, 1 Zahnrad und 1 Eisenplatte. Greifarme bewegen Items zwischen Bändern, Maschinen und Kisten.");
            add("craftorio.quest.build_trading_post", "Baue einen Handelsposten");
            add("craftorio.quest.build_trading_post.hint", "16 Bretter und 4 Eisenplatten. Verkaufen am Handelsposten bringt Credits – sie bezahlen Upgrades in der Tower Defense.");
            add("craftorio.quest.first_sale", "Verkaufe zum ersten Mal etwas");
            add("craftorio.quest.first_sale.hint", "Lege Erz oder Platten in den Handelsposten und drücke Verkaufen.");
            add("craftorio.quest.unlock_assembler", "Erforsche Automatisierung");
            add("craftorio.quest.unlock_assembler.hint", "Automatisierung (10 rote Pakete) schaltet die Montagemaschine frei. Baue erst Labor und rote Pakete und reihe sie dann im Terminal ein.");
            add("craftorio.quest.build_assembler", "Baue eine Montagemaschine");
            add("craftorio.quest.build_assembler.hint", "3 Schaltkreise, 5 Zahnräder und 9 Eisenplatten. Wähle mit den Pfeilen ein Rezept; sie arbeitet mit 75 kW – langsamer als deine Hand, aber ohne Pause.");
            add("craftorio.quest.build_arena_gate", "Baue ein Arena-Tor");
            add("craftorio.quest.build_arena_gate.hint", "8 Eisenplatten, 8 Steinziegel (16 Stein im Steinofen schmelzen) und 2 Schaltkreise. Stelle es auf und rechtsklicke: Es bringt dich in deine eigene Arena. Lege dort mit dem Pfadstab einen Weg vom offenen Tor in der Westmauer zum Kern in der Ostmauer.");
            add("craftorio.quest.build_crossbow_tower", "Baue einen Armbrustturm");
            add("craftorio.quest.build_crossbow_tower.hint", "12 Bretter, 6 Eisenplatten und 4 Zahnräder. Stelle ihn in deiner Arena auf freien Boden neben den Weg und lade ihn mit Bolzen.");
            add("craftorio.quest.unlock_arena_feeder", "Erforsche Geschütztürme");
            add("craftorio.quest.unlock_arena_feeder.hint", "Geschütztürme (10 rote Pakete) schalten den Geschützturm, Munition und den Arena-Einspeiser frei.");
            add("craftorio.quest.build_arena_feeder", "Baue einen Arena-Einspeiser");
            add("craftorio.quest.build_arena_feeder.hint", "In der Arena kann nichts gebaut werden, daher kommen Strom und Munition von außen: Stelle den Arena-Einspeiser in deiner Fabrik auf, verbinde ihn mit dem Stromnetz und führe Bolzen und Patronen per Band oder Greifarm zu. Das Arena-HUD zeigt, was angekommen ist.");
            add("craftorio.quest.unlock_cave_entrance", "Erforsche den Höhlenzugang");
            add("craftorio.quest.unlock_cave_entrance.hint", "Höhlenzugang (100 rote Pakete, braucht Motoren und den Bohrkern aus Tower-Defense-Level 10) schaltet den Höhleneingang frei.");
            add("craftorio.quest.build_cave_entrance", "Baue den Höhleneingang");
            add("craftorio.quest.build_cave_entrance.hint", "Baue ihn an der Oberfläche (y ≥ 50) und liefere die benötigten Materialien; der Schacht bohrt sich in die Höhlen.");
            add("craftorio.quest.unlock_elevator", "Erforsche Warenaufzüge");
            add("craftorio.quest.unlock_elevator.hint", "Warenaufzüge (50 rote Pakete) transportieren Items zwischen den Ebenen.");
            add("craftorio.quest.unlock_mine_shaft", "Erforsche den Minenschacht");
            add("craftorio.quest.unlock_mine_shaft.hint", "Minenschacht (300 rote Pakete, braucht den Tiefenkern aus Tower-Defense-Level 30) schaltet den Weg in die Minen frei.");
            add("craftorio.quest.mine_oak_log", "Baue 10 Holz ab");
            add("craftorio.quest.mine_oak_log.hint", "Holzfelder sind Erzfelder aus Stämmen, die nie leer werden: von Hand abbauen oder einen Bohrer daraufsetzen. Holz brauchst du für Strommasten.");
            add("craftorio.quest.build_terminal", "Baue ein Terminal");
            add("craftorio.quest.build_terminal.hint", "5 Eisenplatten und 2 Schaltkreise. Am Terminal reihst du Forschungen ein, holst Leitfaden-Belohnungen ab und steuerst die Tower Defense.");
            add("craftorio.research.logistics", "Logistik");
            add("craftorio.research.fast_inserters", "Schnelle Greifarme");
            add("craftorio.splitter.filter_set", "Splitter-Filter: %s geht %s, alles andere wechselt zwischen den anderen Ausgängen");
            add("craftorio.splitter.filter_cleared", "Splitter-Filter gelöscht");
            add("craftorio.splitter.no_filter", "Kein Filter: Rechtsklick mit einem Item setzt einen");
            add("craftorio.splitter.output.front", "geradeaus");
            add("craftorio.splitter.output.left", "nach links");
            add("craftorio.splitter.output.right", "nach rechts");
            add("craftorio.hint.belt.1", "Neigung");
            add("craftorio.hint.underground.1", "Ausgang in Linie, max. 4 Blöcke");
            add("craftorio.hint.splitter.1", "Filter setzen (Item in Hand)");
            add("craftorio.hint.splitter.2", "Filter-Richtung (leere Hand)");
            add("craftorio.hint.splitter.3", "Filter löschen");
            add("craftorio.hint.filter_inserter.1", "Filter setzen (Item in Hand)");
            add("craftorio.hint.filter_inserter.2", "Filter löschen");
            add("craftorio.hint.path_wand.1", "Weg legen / Linie");
            add("craftorio.hint.path_wand.2", "Weg entfernen");
            add("craftorio.hint.path_wand.3", "Route zeigen (in die Luft)");
            add("craftorio.hint.guide.1", "Handbuch");
            add("craftorio.inserter.filter_set", "Filter: nur %s");
            add("craftorio.inserter.filter_cleared", "Filter gelöscht");
            add("craftorio.inserter.no_filter", "Kein Filter: Item in die Hand nehmen und rechtsklicken");
            add("craftorio.quest.unlock_underground_belt", "Erforsche Logistik");
            add("craftorio.quest.unlock_underground_belt.hint", "Logistik (75 rote Pakete) schaltet das Unterflurband und den Splitter frei. Ein Unterflurband besteht aus zwei Teilen: Setze das zweite bis zu 4 Blöcke hinter das erste in dieselbe Linie, dann wird es zum Ausgang.");
            add("craftorio.quest.build_splitter", "Baue einen Splitter");
            add("craftorio.quest.build_splitter.hint", "5 Schaltkreise, 5 Eisenplatten und 4 Bänder. Von hinten füttern: Items wechseln zwischen vorne, links und rechts. Items wechseln zwischen den angeschlossenen Ausgängen. Rechtsklick mit einem Item setzt einen Filter, Rechtsklick mit leerer Hand bestimmt, wohin das gefilterte Item geht, Schleichen + Rechtsklick löscht den Filter.");
            add("block.craftorio.underground_belt", "Unterflurband");
            add("block.craftorio.fast_underground_belt", "Schnelles Unterflurband");
            add("block.craftorio.splitter", "Splitter");
            add("block.craftorio.fast_splitter", "Schneller Splitter");
            add("block.craftorio.long_inserter", "Langer Greifarm");
            add("block.craftorio.fast_inserter", "Schneller Greifarm");
            add("block.craftorio.filter_inserter", "Filter-Greifarm");
            add("craftorio.quest.next", "Als Nächstes");
            add("craftorio.hud.guide", "Leitfaden: %s");
            add("craftorio.hud.guide_done", "Leitfaden: %s ✔ – mit G abholen");
            add("craftorio.quest.claim", "Abholen");
            add("craftorio.quest.done", "Erledigt ✔");
            add("craftorio.quest.ready", "Erreicht!");
            add("craftorio.quest.open", "Noch offen");
            add("craftorio.quest.not_done", "Dieses Ziel ist noch nicht erreicht.");
            add("craftorio.quest.claimed", "Leitfaden: %s – %s erhalten");
        }
    }
}
